# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbEquipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equ_wip', models.IntegerField(default=0, verbose_name='WIP (Dias Produção)')),
                ('equ_ordem_codigo', models.IntegerField(verbose_name='Ordem')),
                ('equ_ordem_descricao', models.CharField(max_length=60, verbose_name='Descrição da Ordem')),
                ('equ_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('equ_fonte', models.FileField(blank=True, null=True, upload_to='fontes', verbose_name='Fonte')),
                ('valor_inicial_1', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Inicial Paradas Não Programadas (%)')),
                ('valor_inicial_2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial Produtividade')),
                ('valor_inicial_3', models.BooleanField(default=True, verbose_name='Valor Inicial Running')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Ordem de Producao',
                'verbose_name_plural': ' Ordem de Produção',
                'ordering': ['equ_codigo', 'equ_ordem_codigo'],
            },
        ),
        migrations.CreateModel(
            name='TbEquipamentosCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equ_cad_codigo', models.CharField(max_length=20, verbose_name='Equipamento')),
                ('equ_cad_descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('equ_cad_gargalo', models.BooleanField(default=True, verbose_name='Gargalo')),
                ('equ_cad_expedicao', models.BooleanField(default=False, verbose_name='Expedição')),
                ('equ_cad_output', models.CharField(choices=[('un', 'un'), ('pe', 'pe'), ('g', 'g'), ('kg', 'kg'), ('t', 't'), ('h', 'h'), ('hh', 'hh'), ('m', 'm'), ('m3', 'm3'), ('Nm3', 'Nm3'), ('L', 'L'), ('kw', 'kw'), ('kwh', 'kwh'), ('Mwh', 'Mwh')], max_length=3, verbose_name='Output')),
                ('equ_cad_imagem', models.ImageField(blank=True, null=True, upload_to='equipamentos', verbose_name='Imagem')),
                ('equ_cad_moeda_manutencao', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], max_length=3, verbose_name='Moeda Custo Manutenção')),
                ('valor_inicial_1', models.BooleanField(default=True, verbose_name='Valor Inicial Running')),
                ('valor_inicial_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor Inicial Paradas Programadas (%)')),
                ('valor_inicial_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Valor Inicial Manutenção')),
                ('equ_cad_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('equ_cad_fonte', models.FileField(blank=True, null=True, upload_to='fontes', verbose_name='Fonte')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '  Cadastro',
                'verbose_name_plural': '  Cadastro',
                'ordering': ['equ_cad_codigo'],
            },
        ),
        migrations.CreateModel(
            name='TbEquipamentosCadastroDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.BooleanField(default=True, verbose_name='Running')),
                ('dau_valor_2', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Paradas Programadas (%)')),
                ('dau_valor_3', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Custo Manutenção (Moeda/h)')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbEquipamentosConsumoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equ_con_esp_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('valor_inicial', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Valor Inicial do Consumo Específico')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consumo Específico',
                'verbose_name_plural': 'Consumos Específicos',
                'ordering': ['equ_con_esp_equipamento', 'equ_con_esp_custoitempreco'],
            },
        ),
        migrations.CreateModel(
            name='TbEquipamentosConsumoEspecificoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=4, default=0, max_digits=11, verbose_name='Consumo Específico')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbEquipamentosDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paradas Não Prog. (%)')),
                ('dau_valor_2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Produtividade')),
                ('dau_valor_3', models.BooleanField(default=True, verbose_name='Running')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tbequipamentos', verbose_name='Equipamentos')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
    ]
