# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('custo_ferbasa', '0001_initial'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbequipamentosdaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbequipamentosconsumoespecificodaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tbequipamentosconsumoespecifico', verbose_name='Equipamento/Item'),
        ),
        migrations.AddField(
            model_name='tbequipamentosconsumoespecificodaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbequipamentosconsumoespecifico',
            name='equ_con_consumo_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custo_ferbasa.tbconsumoespecifico', verbose_name='Consumo Específico CF'),
        ),
    ]
