# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('tabelas', '0001_initial'),
        ('equipamentos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbequipamentosconsumoespecifico',
            name='equ_con_esp_custoitempreco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcustoitempreco', verbose_name='Item de Custo / Planta'),
        ),
        migrations.AddField(
            model_name='tbequipamentosconsumoespecifico',
            name='equ_con_esp_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tbequipamentos', verbose_name='Equipamento / Ordem / Descrição'),
        ),
        migrations.AddField(
            model_name='tbequipamentosconsumoespecifico',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbequipamentoscadastrodaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tbequipamentoscadastro', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='tbequipamentoscadastrodaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbequipamentoscadastro',
            name='equ_cad_indicador_manutencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbindicadores', verbose_name='Indicador Custo Manutenção'),
        ),
        migrations.AddField(
            model_name='tbequipamentoscadastro',
            name='equ_cad_unidade_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbunidadeproducao', verbose_name='Planta'),
        ),
        migrations.AddField(
            model_name='tbequipamentoscadastro',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbequipamentos',
            name='equ_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tbequipamentoscadastro', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='tbequipamentos',
            name='equ_tipo_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbtipoproducao', verbose_name='Tipo Produção'),
        ),
        migrations.AddField(
            model_name='tbequipamentos',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AlterUniqueTogether(
            name='tbequipamentosconsumoespecifico',
            unique_together={('equ_con_esp_equipamento', 'equ_con_esp_custoitempreco', 'tbcenarios')},
        ),
    ]
