# Generated by Django 4.1.7 on 2024-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbequipamentosdaugther',
            name='dau_valor_2',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Produtividade'),
        ),
    ]
