# Generated by Django 4.1.7 on 2025-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_alter_tbequipamentosdaugther_dau_valor_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbequipamentosdaugther',
            name='dau_valor_3',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
