# Generated by Django 4.2.30 on 2026-09-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0002_alter_tbcapex_cap_indicador_and_more'),
        ('equipamentos', '0005_alter_tbequipamentosdaugther_dau_valor_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbequipamentoscadastro',
            name='equ_cad_indicador_manutencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.tbindicadores', verbose_name='Indicador Custo Manutenção'),
        ),
    ]
