# Generated by Django 4.2.30 on 2026-09-28 00:56

from django.db import migrations, models
import django.db.models.deletion
import parameters.contexto_usuario


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_alter_tbcustoitem_cus_ite_tipo_and_more'),
        ('equipamentos', '0006_alter_tbequipamentoscadastro_equ_cad_indicador_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbequipamentos',
            name='equ_tipo_producao',
            field=models.ForeignKey(limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbtipoproducao', verbose_name='Tipo Produção'),
        ),
        migrations.AlterField(
            model_name='tbequipamentoscadastro',
            name='equ_cad_unidade_producao',
            field=models.ForeignKey(limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbunidadeproducao', verbose_name='Planta'),
        ),
    ]
