# Generated by Django 4.2.30 on 2026-09-30 19:50

from django.db import migrations, models
import django.db.models.deletion
import parameters.contexto_usuario


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_tbmercadooutbound_mer_out_indicador'),
        ('tabelas', '0004_alter_tbcustoitem_cus_ite_tipo_and_more'),
        ('equipamentos', '0007_alter_tbequipamentos_equ_tipo_producao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbequipamentos',
            name='equ_produtos',
            field=models.ManyToManyField(blank=True, limit_choices_to=parameters.contexto_usuario.limit_choices_to_cenario_ativo, to='produtos.tbprodutos', verbose_name='Produtos Participantes'),
        ),
        migrations.AlterField(
            model_name='tbequipamentos',
            name='equ_tipo_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbtipoproducao', verbose_name='Tipo Produção'),
        ),
        migrations.AlterField(
            model_name='tbequipamentoscadastro',
            name='equ_cad_unidade_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbunidadeproducao', verbose_name='Planta'),
        ),
    ]
