# Generated by Django 4.2.30 on 2026-10-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0008_tbequipamentos_equ_produtos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbequipamentoscadastro',
            name='equ_cad_gera_fluxo_novo',
            field=models.BooleanField(default=True, verbose_name='Gera Novo Fluxo'),
        ),
    ]
