# Generated by Django 4.2.30 on 2026-10-02 08:41

from django.db import migrations, models
import django.db.models.deletion


def criar_quebra_fluxo_padrao(apps, schema_editor):
    """
    🌟 NOVO: cria UM registro "padrão" de TbQuebraFluxo (sem empresa
    definida -- o campo é opcional) só pra servir de valor inicial aos
    equipamentos já cadastrados (ver o AddField logo abaixo, que usa
    default=1). Depois da migration, cada usuário pode trocar o "Quebra
    Fluxo" de cada equipamento pelo valor correto no Admin.
    """
    TbQuebraFluxo = apps.get_model('equipamentos', 'TbQuebraFluxo')
    TbQuebraFluxo.objects.get_or_create(
        que_flu_nome='PADRÃO',
        empresa=None,
        defaults={'que_flu_gera_novo_fluxo': True},
    )


def reverter_quebra_fluxo_padrao(apps, schema_editor):
    """Reversão: remove o registro padrão, se ele ainda existir."""
    TbQuebraFluxo = apps.get_model('equipamentos', 'TbQuebraFluxo')
    TbQuebraFluxo.objects.filter(que_flu_nome='PADRÃO', empresa=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0042_remove_perfilusuario_telefone_whatsapp'),
        ('equipamentos', '0009_tbequipamentoscadastro_equ_cad_gera_fluxo_novo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbequipamentoscadastro',
            name='equ_cad_gera_fluxo_novo',
        ),
        migrations.CreateModel(
            name='TbQuebraFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_flu_nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('que_flu_gera_novo_fluxo', models.BooleanField(default=True, verbose_name='Gera Novo Fluxo')),
                ('que_flu_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Quebra de Fluxo',
                'verbose_name_plural': 'Quebras de Fluxo',
                'ordering': ['que_flu_nome'],
            },
        ),
        # 🌟 NOVO: cria o registro padrão ANTES do AddField abaixo --
        # sem isso, o default=1 do AddField aponta pra um id que ainda
        # não existe (a tabela acabou de ser criada, vazia).
        migrations.RunPython(criar_quebra_fluxo_padrao, reverter_quebra_fluxo_padrao),
        migrations.AddField(
            model_name='tbequipamentos',
            name='equ_quebra_fluxo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tbquebrafluxo', verbose_name='Quebra Fluxo'),
            preserve_default=False,
        ),
    ]