# Generated by Django 4.2.30 on 2026-10-02 15:34

from django.db import migrations, models
import django.db.models.deletion
import parameters.contexto_usuario


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0005_tbtipoproducao_tip_critério_para_quebra_fluxo'),
        ('equipamentos', '0010_remove_tbequipamentoscadastro_equ_cad_gera_fluxo_novo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbequipamentos',
            name='equ_quebra_fluxo',
        ),
        migrations.AlterField(
            model_name='tbequipamentos',
            name='equ_tipo_producao',
            field=models.ForeignKey(limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbtipoproducao', verbose_name='Tipo Produção'),
        ),
        migrations.AlterField(
            model_name='tbequipamentoscadastro',
            name='equ_cad_unidade_producao',
            field=models.ForeignKey(limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbunidadeproducao', verbose_name='Planta'),
        ),
        migrations.DeleteModel(
            name='TbQuebraFluxo',
        ),
    ]
