# Generated by Django 4.2.30 on 2026-10-02 22:14

from django.db import migrations, models
import django.db.models.deletion
import parameters.contexto_usuario


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0011_remove_tbequipamentos_equ_quebra_fluxo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbequipamentos',
            name='equ_e_clone_de',
            field=models.ForeignKey(blank=True, limit_choices_to=parameters.contexto_usuario.limit_choices_to_cenario_ativo, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='equipamentos.tbequipamentos', verbose_name='É Clone Da Ordem'),
        ),
    ]
