# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbFluxoConsumoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flu_con_pad_descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('flu_con_pad_validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('flu_con_pad_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('valor_inicial', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Valor Inicial Consumo Padrão')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '   Consumo Padrão',
                'verbose_name_plural': '   Consumos Padrões',
                'ordering': ['flu_con_pad_from_equipamento', 'flu_con_pad_to_equipamento'],
            },
        ),
        migrations.CreateModel(
            name='TbFluxoConsumoPadraoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=4, default=0, max_digits=11, verbose_name='Consumo Padrão')),
            ],
            options={
                'verbose_name': 'Consumo Padrão Previsto',
                'verbose_name_plural': 'Consumos Padrões Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbFluxoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flu_pro_descricao', models.CharField(max_length=130, verbose_name='Descrição')),
                ('flu_pro_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('flu_pro_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('flu_pro_erro', models.TextField(blank=True, null=True, verbose_name='Erro(s)')),
                ('flu_pro_pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_file', verbose_name='Fluxo (PDF)')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Fluxo de Produção',
                'verbose_name_plural': ' Fluxos de Produção',
                'ordering': ['flu_pro_produto', 'flu_pro_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbFluxoProducaoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flu_pro_dau_coluna', models.IntegerField(verbose_name='Coluna')),
                ('flu_pro_dau_linha', models.IntegerField(verbose_name='Linha')),
                ('flu_pro_dau_margem_horaria', models.BooleanField(default=False, verbose_name='Margem Horária')),
            ],
            options={
                'verbose_name': 'Sequenciamento da Produção',
                'verbose_name_plural': 'Sequenciamento da Produção',
                'ordering': ['flu_pro_dau_coluna', 'flu_pro_dau_linha'],
            },
        ),
        migrations.CreateModel(
            name='TbFluxoProducaoDaugther01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.BooleanField(default=True, verbose_name='Running')),
            ],
            options={
                'verbose_name': 'Detalhes por Período',
                'verbose_name_plural': 'Detalhes por Período',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbFluxoProducaoInputOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flu_pro_inp_out_coluna', models.IntegerField(verbose_name='Coluna')),
                ('flu_pro_inp_out_linha', models.IntegerField(verbose_name='Linha')),
                ('flag', models.BooleanField(default=False, verbose_name='Ativo')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalhamento por Equipamento',
                'verbose_name_plural': 'Detalhamento por Equipamento',
                'ordering': ['flu_pro_inp_out_coluna', 'flu_pro_inp_out_linha'],
            },
        ),
        migrations.CreateModel(
            name='TbFluxoProducaoInputOutputDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_3', models.DecimalField(decimal_places=4, default=0, max_digits=11, verbose_name='Output Padrão')),
                ('dau_valor_4', models.DecimalField(decimal_places=4, default=0, max_digits=11, verbose_name='Output Real')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.tbfluxoproducaoinputoutput', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Detalhe por Período (click e use setas para direita e esquerda)',
                'verbose_name_plural': 'Detalhes por Período (click e use setas para direita e esquerda)',
                'ordering': ['dau_order'],
            },
        ),
    ]
