# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('equipamentos', '0002_initial'),
        ('fluxos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducaoinputoutputdaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaoinputoutput',
            name='flu_pro_inp_out_envia_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flu_pro_inp_out_envia_para', to='equipamentos.tbequipamentos', verbose_name='Envia para'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaoinputoutput',
            name='flu_pro_inp_out_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flu_pro_inp_out_equipamento', to='equipamentos.tbequipamentos', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaoinputoutput',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.tbfluxoproducao', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaoinputoutput',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaodaugther01',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.tbfluxoproducao', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaodaugther01',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaodaugther',
            name='flu_pro_dau_consumo_padrao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.tbfluxoconsumopadrao', verbose_name='From --> To'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaodaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.tbfluxoproducao', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaodaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_copiar_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxos.tbfluxoproducao', verbose_name='Copiar de'),
        ),
    ]
