# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0002_initial'),
        ('parameters', '0001_initial'),
        ('custo_ferbasa', '0001_initial'),
        ('fluxos', '0002_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.tbprodutos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbfluxoconsumopadraodaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.tbfluxoconsumopadrao', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbfluxoconsumopadraodaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbfluxoconsumopadrao',
            name='flu_con_pad_consumo_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custo_ferbasa.tbconsumoespecifico', verbose_name='Consumo Específico'),
        ),
        migrations.AddField(
            model_name='tbfluxoconsumopadrao',
            name='flu_con_pad_from_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flu_con_pad_from_equipamento', to='equipamentos.tbequipamentos', verbose_name='From'),
        ),
        migrations.AddField(
            model_name='tbfluxoconsumopadrao',
            name='flu_con_pad_to_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flu_con_pad_to_equipamento', to='equipamentos.tbequipamentos', verbose_name='To'),
        ),
        migrations.AddField(
            model_name='tbfluxoconsumopadrao',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.CreateModel(
            name='TbFluxoProducao01',
            fields=[
            ],
            options={
                'verbose_name': 'Detalhe Fluxo/Equipamento',
                'verbose_name_plural': 'Detalhes Fluxo/Equipamento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fluxos.tbfluxoproducao',),
        ),
        migrations.AlterUniqueTogether(
            name='tbfluxoconsumopadrao',
            unique_together={('flu_con_pad_descricao', 'tbcenarios')},
        ),
    ]
