# Generated by Django 4.1.7 on 2025-01-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_copiar_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluxos.tbfluxoproducao', verbose_name='Copiar de'),
        ),
    ]
