# Generated by Django 4.1.7 on 2025-02-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0004_alter_tbfluxoproducao_flu_pro_copiar_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfluxoconsumopadrao',
            name='flu_con_pad_descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
