# Generated by Django 4.1.7 on 2025-03-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0005_alter_tbfluxoconsumopadrao_flu_con_pad_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_input_output_atualizado',
            field=models.BooleanField(default=False, verbose_name='I/O Atualizado'),
        ),
    ]
