# Generated by Django 4.1.7 on 2025-03-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0006_tbfluxoproducao_flu_pro_input_output_atualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_custo_variavel_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Custo Variável Médio'),
        ),
    ]
