# Generated by Django 4.1.7 on 2025-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0007_tbfluxoproducao_flu_pro_custo_variavel_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducaodaugther01',
            name='custo_variavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Custo Variável'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaodaugther01',
            name='custo_variavel_inbound',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='`Parcela Inbound`'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaodaugther01',
            name='custo_variavel_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='`Parcela Itens`'),
        ),
        migrations.AddField(
            model_name='tbfluxoproducaodaugther01',
            name='custo_variavel_manutencao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='`Parcela Manutencão`'),
        ),
    ]
