# Generated by Django 4.1.7 on 2025-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0008_tbfluxoproducaodaugther01_custo_variavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
    ]
