# Generated by Django 4.1.7 on 2025-03-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0009_alter_tbfluxoproducao_flu_pro_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_descricao',
            field=models.CharField(max_length=140, verbose_name='Descrição'),
        ),
    ]
