# Generated by Django 4.1.7 on 2025-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0011_alter_tbfluxoproducao_flu_pro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_sequencia_atualizada',
            field=models.BooleanField(default=False, verbose_name='Sequência Atualizada'),
        ),
    ]
