# Generated by Django 4.1.7 on 2025-03-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0012_tbfluxoproducao_flu_pro_sequencia_atualizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbfluxoproducao',
            name='flu_pro_sequencia_atualizada',
        ),
    ]
