# Generated by Django 4.1.7 on 2025-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0013_remove_tbfluxoproducao_flu_pro_sequencia_atualizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_erro',
            field=models.CharField(blank=True, default='SIM', max_length=3, null=True, verbose_name='Erro(s)'),
        ),
    ]
