# Generated by Django 4.1.7 on 2025-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0014_alter_tbfluxoproducao_flu_pro_erro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_erro',
            field=models.CharField(default='SIM', max_length=3, verbose_name='Erro(s)'),
        ),
    ]
