# Generated by Django 4.1.7 on 2025-05-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0017_alter_equipment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(upload_to='equipamentos/')),
                ('capacidade_producao', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('posicao_x', models.IntegerField(default=0)),
                ('posicao_y', models.IntegerField(default=0)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FluxoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='ProductionFlow',
        ),
        migrations.AddField(
            model_name='etapaproducao',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='fluxos.fluxoproducao'),
        ),
    ]
