# Generated by Django 4.1.7 on 2025-05-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0018_equipamento_etapaproducao_fluxoproducao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='capacidade_producao',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='capacidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='equipamentos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='equipamentos/'),
        ),
        migrations.DeleteModel(
            name='EtapaProducao',
        ),
    ]
