# Generated by Django 4.1.7 on 2025-05-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0019_remove_equipamento_capacidade_producao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
