# Generated by Django 4.1.7 on 2025-05-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0021_equipamento_fluxoproducao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
