# Generated by Django 4.1.7 on 2025-05-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0023_equipamento_fluxoproducao_etapafluxo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='equipamentos')),
                ('specifications', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('step_order', models.IntegerField()),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipment')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='EtapaFluxo',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
        migrations.AddField(
            model_name='flowstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='fluxos.productionflow'),
        ),
    ]
