# Generated by Django 4.1.7 on 2025-05-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0024_equipment_flowstep_productionflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowstep',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='flowstep',
            name='flow',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='FlowStep',
        ),
        migrations.DeleteModel(
            name='ProductionFlow',
        ),
    ]
