# Generated by Django 4.1.7 on 2025-05-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0026_equipment_productionflow_productionstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=50)),
                ('data_instalacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FluxoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], max_length=50)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='fluxos.equipamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='productionstep',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='productionstep',
            name='flow',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='ProductionFlow',
        ),
        migrations.DeleteModel(
            name='ProductionStep',
        ),
    ]
