# Generated by Django 4.1.7 on 2025-05-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0027_equipamento_fluxoproducao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='equipamento',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
