# Generated by Django 4.1.7 on 2025-05-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0029_equipamento_fluxoproducao_sequenciaequipamento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequenciaequipamento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tempo_processamento',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='atualizado_em',
        ),
        migrations.AddField(
            model_name='sequenciaequipamento',
            name='posicao_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sequenciaequipamento',
            name='posicao_y',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='sequenciaequipamento',
            name='configuracao',
        ),
    ]
