# Generated by Django 4.1.7 on 2025-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0030_alter_sequenciaequipamento_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenciaequipamento',
            name='posicao_x',
        ),
        migrations.RemoveField(
            model_name='sequenciaequipamento',
            name='posicao_y',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='capacidade_producao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tempo_setup',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sequenciaequipamento',
            name='tempo_processamento',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
