# Generated by Django 4.1.7 on 2025-05-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0031_remove_sequenciaequipamento_posicao_x_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='capacidade_producao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tempo_setup',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='descricao',
        ),
        migrations.AlterUniqueTogether(
            name='sequenciaequipamento',
            unique_together={('fluxo', 'ordem')},
        ),
        migrations.RemoveField(
            model_name='sequenciaequipamento',
            name='tempo_processamento',
        ),
    ]
