# Generated by Django 4.1.7 on 2025-05-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0032_alter_equipamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('posicao_x', models.IntegerField(default=0)),
                ('posicao_y', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipamento',
            options={},
        ),
        migrations.RenameField(
            model_name='fluxoproducao',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='equipamentos',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='capacidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tempo_processamento',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SequenciaEquipamento',
        ),
        migrations.AddField(
            model_name='etapafluxo',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento'),
        ),
        migrations.AddField(
            model_name='etapafluxo',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='fluxos.fluxoproducao'),
        ),
    ]
