# Generated by Django 4.1.7 on 2025-05-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0033_etapafluxo_alter_equipamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapafluxo',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tempo_processamento',
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='descricao',
        ),
    ]
