# Generated by Django 4.1.7 on 2025-05-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0034_alter_etapafluxo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='etapafluxo',
            options={'ordering': ['ordem'], 'verbose_name_plural': 'Etapas do Fluxo'},
        ),
        migrations.AlterModelOptions(
            name='fluxoproducao',
            options={'verbose_name_plural': 'Fluxos de Produção'},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etapafluxo',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etapafluxo',
            name='pos_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etapafluxo',
            name='pos_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fluxoproducao',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='etapafluxo',
            unique_together={('fluxo', 'ordem'), ('fluxo', 'equipamento')},
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='posicao_x',
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='posicao_y',
        ),
    ]
