# Generated by Django 4.1.7 on 2025-05-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0035_alter_equipamento_options_alter_etapafluxo_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='etapafluxo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='EtapaFluxo',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
