# Generated by Django 4.1.7 on 2025-05-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0039_equipamento_fluxoproducao_etapafluxo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapafluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='EtapaFluxo',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
