# Generated by Django 4.1.7 on 2025-05-04 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0042_remove_etapafluxo_equipamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('width', models.IntegerField(default=100)),
                ('height', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('connections', models.ManyToManyField(blank=True, to='fluxos.flowcomponent')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipment')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='fluxos.productionflow')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
