# Generated by Django 4.1.7 on 2025-05-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0043_equipment_productionflow_flowcomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowcomponent',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='flowcomponent',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='flowcomponent',
            name='flow',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='FlowComponent',
        ),
        migrations.DeleteModel(
            name='ProductionFlow',
        ),
    ]
