# Generated by Django 4.1.7 on 2025-05-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0045_equipamento_fluxoproducao_itemfluxo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfluxo',
            name='conexoes',
        ),
        migrations.RemoveField(
            model_name='itemfluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='itemfluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
        migrations.DeleteModel(
            name='ItemFluxo',
        ),
    ]
