# Generated by Django 4.1.7 on 2025-05-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0047_equipamento_fluxoproducao_posicaoequipamento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conexaoequipamento',
            unique_together={('origem', 'destino')},
        ),
        migrations.RemoveField(
            model_name='conexaoequipamento',
            name='fluxo',
        ),
    ]
