# Generated by Django 4.1.7 on 2025-05-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0048_alter_conexaoequipamento_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='equipamentos',
        ),
        migrations.AddField(
            model_name='conexaoequipamento',
            name='fluxo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxos.fluxoproducao'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(upload_to='equipamentos/'),
        ),
    ]
