# Generated by Django 4.1.7 on 2025-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0049_remove_equipamento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoproducao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posicaoequipamento',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posicaoequipamento',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
