# Generated by Django 4.1.7 on 2025-05-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0050_fluxoproducao_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicaoequipamento',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='posicaoequipamento',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='ConexaoEquipamento',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
        migrations.DeleteModel(
            name='PosicaoEquipamento',
        ),
    ]
