# Generated by Django 4.1.7 on 2025-05-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0051_remove_posicaoequipamento_equipamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='equipamentos/')),
            ],
        ),
        migrations.CreateModel(
            name='FluxoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.fluxoproducao')),
            ],
        ),
        migrations.CreateModel(
            name='ConexaoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_destino', to='fluxos.etapafluxo')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.fluxoproducao')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_origem', to='fluxos.etapafluxo')),
            ],
        ),
    ]
