# Generated by Django 4.1.7 on 2025-05-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0052_equipamento_fluxoproducao_etapafluxo_conexaofluxo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NodoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='fluxos.fluxoproducao')),
            ],
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='ConexaoFluxo',
        ),
        migrations.DeleteModel(
            name='EtapaFluxo',
        ),
        migrations.AddField(
            model_name='conexao',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_destino', to='fluxos.nodofluxo'),
        ),
        migrations.AddField(
            model_name='conexao',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='fluxos.fluxoproducao'),
        ),
        migrations.AddField(
            model_name='conexao',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_origem', to='fluxos.nodofluxo'),
        ),
    ]
