# Generated by Django 4.1.7 on 2025-05-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0053_conexao_nodofluxo_remove_etapafluxo_equipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodofluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='nodofluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Conexao',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
        migrations.DeleteModel(
            name='NodoFluxo',
        ),
    ]
