# Generated by Django 4.1.7 on 2025-05-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0055_equipamento_fluxoproducao_equipamentonofluxo_conexao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamentonofluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='equipamentonofluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Conexao',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='EquipamentoNoFluxo',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
