# Generated by Django 4.1.7 on 2025-05-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0057_equipamento_fluxoproducao_itemfluxo_conexao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='itemfluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Conexao',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
        migrations.DeleteModel(
            name='ItemFluxo',
        ),
    ]
