# Generated by Django 4.1.7 on 2025-05-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0058_remove_itemfluxo_equipamento_remove_itemfluxo_fluxo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='equipamentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Fluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='fluxos.fluxo')),
            ],
        ),
    ]
