# Generated by Django 4.1.7 on 2025-05-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0059_equipamento_fluxo_etapafluxo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapafluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='EtapaFluxo',
        ),
        migrations.DeleteModel(
            name='Fluxo',
        ),
    ]
