# Generated by Django 4.1.7 on 2025-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0061_equipamento_fluxoproducao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxoproducao',
            old_name='dados_json',
            new_name='dados_fluxo',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fluxoproducao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
