# Generated by Django 4.1.7 on 2025-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0062_rename_dados_json_fluxoproducao_dados_fluxo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoproducao',
            name='dados_fluxo',
            field=models.JSONField(default=dict),
        ),
    ]
