# Generated by Django 4.1.7 on 2025-05-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0063_alter_fluxoproducao_dados_fluxo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
