# Generated by Django 4.1.7 on 2025-05-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0064_delete_equipamento_delete_fluxoproducao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='equipamentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Fluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dados_json', models.JSONField(default=dict)),
            ],
        ),
    ]
