# Generated by Django 4.1.7 on 2025-05-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0065_equipamento_fluxo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxo',
            name='dados_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
