# Generated by Django 4.1.7 on 2025-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0066_alter_fluxo_dados_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxo',
            name='dados_json',
            field=models.JSONField(default=dict),
        ),
    ]
