# Generated by Django 4.1.7 on 2025-05-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0068_equipment_productionflow_delete_equipamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='ProductionFlow',
        ),
    ]
