# Generated by Django 4.1.7 on 2025-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0069_delete_equipment_delete_productionflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='equipamentos/')),
            ],
        ),
        migrations.CreateModel(
            name='FluxoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dados_json', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
