# Generated by Django 4.1.7 on 2025-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0070_equipamento_fluxoproducao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoproducao',
            name='dados_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
