# Generated by Django 4.1.7 on 2025-05-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0071_alter_fluxoproducao_dados_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
