# Generated by Django 4.1.7 on 2025-05-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0073_equipamento_fluxo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='Fluxo',
        ),
    ]
