# Generated by Django 4.1.7 on 2025-05-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0075_productionflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionFlow',
        ),
    ]
