# Generated by Django 4.1.7 on 2025-05-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0077_productionflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='equipment/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
