# Generated by Django 4.1.7 on 2025-05-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0078_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='ProductionFlow',
        ),
    ]
