# Generated by Django 4.1.7 on 2025-05-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0080_equipamento_fluxoproducao_equipamentonofluxo_conexao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexao',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='fluxos.equipamentonofluxo'),
        ),
        migrations.AlterField(
            model_name='conexao',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='fluxos.equipamentonofluxo'),
        ),
        migrations.AlterField(
            model_name='equipamentonofluxo',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipamentonofluxo',
            name='y',
            field=models.FloatField(),
        ),
    ]
