# Generated by Django 4.1.7 on 2025-05-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0081_alter_conexao_destino_alter_conexao_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexao',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='fluxos.equipamentonofluxo'),
        ),
        migrations.AlterField(
            model_name='conexao',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origens', to='fluxos.equipamentonofluxo'),
        ),
        migrations.AlterField(
            model_name='equipamentonofluxo',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipamentonofluxo',
            name='y',
            field=models.IntegerField(),
        ),
    ]
