# Generated by Django 4.1.7 on 2025-05-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0082_alter_conexao_destino_alter_conexao_origem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamentonofluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='equipamentonofluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Conexao',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='EquipamentoNoFluxo',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
