# Generated by Django 4.1.7 on 2025-05-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0084_equipamento_fluxoproducao_nofluxo_conexaofluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nofluxo',
            name='node_id',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
