# Generated by Django 4.1.7 on 2025-05-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0085_nofluxo_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nofluxo',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.fluxoproducao'),
        ),
        migrations.AlterField(
            model_name='nofluxo',
            name='node_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nofluxo',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nofluxo',
            name='y',
            field=models.FloatField(),
        ),
    ]
