# Generated by Django 4.1.7 on 2025-05-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0086_alter_nofluxo_fluxo_alter_nofluxo_node_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conexaofluxo',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='fluxoproducao',
            name='data_atualizacao',
        ),
        migrations.CreateModel(
            name='ElementoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.IntegerField(verbose_name='Posição X')),
                ('pos_y', models.IntegerField(verbose_name='Posição Y')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='fluxos.fluxoproducao')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='conexaofluxo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_destino', to='fluxos.elementofluxo'),
        ),
        migrations.AlterField(
            model_name='conexaofluxo',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_origem', to='fluxos.elementofluxo'),
        ),
        migrations.DeleteModel(
            name='NoFluxo',
        ),
    ]
