# Generated by Django 4.1.7 on 2025-05-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0087_alter_conexaofluxo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementofluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='elementofluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='ConexaoFluxo',
        ),
        migrations.DeleteModel(
            name='ElementoFluxo',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
