# Generated by Django 4.1.7 on 2025-05-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0089_equipamento_fluxoproducao_equipamentonofluxo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_id_front', models.IntegerField()),
                ('destino_id_front', models.IntegerField()),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='fluxos.fluxoproducao')),
            ],
        ),
        migrations.CreateModel(
            name='FluxoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('id_front', models.IntegerField(help_text='ID do node no frontend')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fluxos.fluxoproducao')),
            ],
            options={
                'unique_together': {('fluxo', 'id_front')},
            },
        ),
        migrations.RemoveField(
            model_name='equipamentonofluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='equipamentonofluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='ConexaoEquipamento',
        ),
        migrations.DeleteModel(
            name='EquipamentoNoFluxo',
        ),
    ]
