# Generated by Django 4.1.7 on 2025-05-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0090_conexao_fluxoequipamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoConexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FluxoNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.fluxoproducao')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fluxoequipamento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fluxoequipamento',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='fluxoequipamento',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Conexao',
        ),
        migrations.DeleteModel(
            name='FluxoEquipamento',
        ),
        migrations.AddField(
            model_name='fluxoconexao',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_destino', to='fluxos.fluxonode'),
        ),
        migrations.AddField(
            model_name='fluxoconexao',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.fluxoproducao'),
        ),
        migrations.AddField(
            model_name='fluxoconexao',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_origem', to='fluxos.fluxonode'),
        ),
    ]
