# Generated by Django 4.1.7 on 2025-05-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0091_fluxoconexao_fluxonode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexaoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_origem', models.CharField(help_text="Nome do ponto de saída no nó de origem (ex: 'output_1')", max_length=100)),
                ('input_destino', models.CharField(help_text="Nome do ponto de entrada no nó de destino (ex: 'input_1')", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('drawflow_node_id', models.CharField(help_text='ID único do nó no Drawflow', max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fluxonode',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='fluxonode',
            name='fluxo',
        ),
        migrations.AddField(
            model_name='fluxoproducao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(upload_to='equipamentos'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fluxoproducao',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='FluxoConexao',
        ),
        migrations.DeleteModel(
            name='FluxoNode',
        ),
        migrations.AddField(
            model_name='equipamentofluxo',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento'),
        ),
        migrations.AddField(
            model_name='equipamentofluxo',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_no_fluxo', to='fluxos.fluxoproducao'),
        ),
        migrations.AddField(
            model_name='conexaofluxo',
            name='equipamento_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_de_entrada', to='fluxos.equipamentofluxo'),
        ),
        migrations.AddField(
            model_name='conexaofluxo',
            name='equipamento_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_de_saida', to='fluxos.equipamentofluxo'),
        ),
        migrations.AddField(
            model_name='conexaofluxo',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_do_fluxo', to='fluxos.fluxoproducao'),
        ),
        migrations.AlterUniqueTogether(
            name='equipamentofluxo',
            unique_together={('fluxo', 'equipamento', 'drawflow_node_id')},
        ),
        migrations.AlterUniqueTogether(
            name='conexaofluxo',
            unique_together={('fluxo', 'equipamento_origem', 'output_origem', 'equipamento_destino', 'input_destino')},
        ),
    ]
