# Generated by Django 4.1.7 on 2025-05-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0092_conexaofluxo_equipamentofluxo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipamentofluxo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='equipamentofluxo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='equipamentofluxo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='ConexaoFluxo',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='EquipamentoFluxo',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
    ]
