# Generated by Django 4.1.7 on 2025-05-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0093_alter_equipamentofluxo_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(null=True, upload_to='equipamentos/')),
            ],
        ),
        migrations.CreateModel(
            name='FluxoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoNoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.equipamento')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.fluxoproducao')),
            ],
        ),
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_destino', to='fluxos.equipamentonofluxo')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.fluxoproducao')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_origem', to='fluxos.equipamentonofluxo')),
            ],
        ),
    ]
