# Generated by Django 4.1.7 on 2025-05-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0096_equipamento_fluxoproducao_fluxoequipamento_conexao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FluxoEquipamento',
            new_name='Nodo',
        ),
    ]
