# Generated by Django 4.1.7 on 2025-05-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0097_rename_fluxoequipamento_nodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='nodo',
            name='fluxo',
        ),
        migrations.DeleteModel(
            name='Conexao',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='FluxoProducao',
        ),
        migrations.DeleteModel(
            name='Nodo',
        ),
    ]
