# Generated by Django 4.1.7 on 2025-05-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0098_remove_nodo_equipamento_remove_nodo_fluxo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_data', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
