# Generated by Django 4.1.7 on 2025-05-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0099_equipment_productionflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='ProductionFlow',
        ),
    ]
