# Generated by Django 4.1.7 on 2025-06-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0100_delete_equipment_delete_productionflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_erro',
            field=models.CharField(default='SIM', max_length=3, verbose_name='Tem Erro'),
        ),
    ]
