# Generated by Django 4.1.7 on 2025-06-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0101_alter_tbfluxoproducao_flu_pro_erro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_dados_fluxo',
            field=models.JSONField(default=dict),
        ),
    ]
