# Generated by Django 5.2.4 on 2025-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0102_tbfluxoproducao_flu_pro_dados_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_data_modificacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
