# Generated by Django 5.2.4 on 2025-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0103_tbfluxoproducao_flu_pro_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_dados_fluxo',
            field=models.JSONField(default=dict, verbose_name='Dados Fluxo'),
        ),
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Criação'),
        ),
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_data_modificacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data Modificação'),
        ),
    ]
