# Generated by Django 5.2.4 on 2026-03-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0104_tbfluxoproducao_flu_pro_nome_and_more'),
        ('parameters', '0012_alter_tbcenarios_cen_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbfluxoproducaoinputoutputdaugther',
            unique_together={('mae', 'dau_order', 'tbcenarios')},
        ),
    ]
