# Generated by Django 4.2.30 on 2026-09-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0105_alter_tbfluxoproducaoinputoutputdaugther_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfluxoproducao',
            name='flu_pro_dados_fluxo',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dados Fluxo'),
        ),
    ]
