# Generated by Django 4.2.30 on 2026-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxos', '0106_alter_tbfluxoproducao_flu_pro_dados_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfluxoproducao',
            name='flu_pro_auto_editor_aut',
            field=models.BooleanField(default=True, help_text='Permite que processos automáticos/Celery atualizem o fluxo salvo no editor.', verbose_name='Permite Atualização Automática'),
        ),
    ]
