# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('custo_ferbasa', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_moeda', models.CharField(choices=[('USD', 'DÓLAR'), ('EUR', 'EURO')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('cam_moeda_imagem', models.ImageField(blank=True, null=True, upload_to='tabelas', verbose_name='Imagem da Moeda')),
                ('cam_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cam_fonte', models.FileField(blank=True, null=True, upload_to='fontes', verbose_name='Fonte')),
                ('valor_inicial', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Valor Inicial')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': '               Taxa de Câmbio',
                'verbose_name_plural': '               Taxas de Câmbio',
                'ordering': ['cam_moeda'],
            },
        ),
        migrations.CreateModel(
            name='TbCapex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cap_recorrente', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('cap_moeda', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('cap_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cap_fonte', models.FileField(blank=True, null=True, upload_to='fontes', verbose_name='Fonte')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Inicial')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '          CAPEX',
                'verbose_name_plural': '          CAPEX',
                'ordering': ['cap_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbCustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('fix_moeda', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('fix_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('fix_fonte', models.FileField(blank=True, null=True, upload_to='fontes', verbose_name='Fonte')),
                ('valor_inicial_1', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Inicial Valor')),
                ('valor_inicial_2', models.IntegerField(verbose_name='Valor Inicial Pagamento (dias)')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '            Custo Fixo',
                'verbose_name_plural': '            Custos Fixos',
                'ordering': ['fix_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbCustoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_ite_nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('cus_ite_codigo_interno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código Interno')),
                ('cus_ite_unidade', models.CharField(choices=[('un', 'un'), ('pe', 'pe'), ('g', 'g'), ('kg', 'kg'), ('t', 't'), ('h', 'h'), ('hh', 'hh'), ('m3', 'm3'), ('Nm3', 'Nm3'), ('L', 'L'), ('kw', 'kw'), ('kwh', 'kwh'), ('Mw', 'Mw'), ('Mwh', 'Mwh')], max_length=3, verbose_name='Unidade')),
                ('cus_ite_imagem', models.ImageField(blank=True, null=True, upload_to='tabelas', verbose_name='Imagem do Item')),
                ('cus_ite_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '     Custo Variável - Item',
                'verbose_name_plural': '    Custo Variável - Itens',
                'ordering': ['cus_ite_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbCustoItemPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_ite_pre_validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('cus_ite_pre_moeda_preco', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], max_length=3, verbose_name='Moeda do Preço')),
                ('cus_ite_pre_moeda_inbound', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], max_length=3, verbose_name='Moeda do Inbound')),
                ('cus_ite_pre_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('valor_inicial_1', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Inicial: Preço')),
                ('valor_inicial_2', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Inicial: Inbound')),
                ('valor_inicial_3', models.IntegerField(verbose_name='Pagamento (dias)')),
                ('valor_inicial_4', models.IntegerField(verbose_name='Pagamento (dias)')),
                ('valor_inicial_5', models.IntegerField(verbose_name='Estoque (dias)')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
                ('cus_ite_pre_custo_variavel_adiconado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custo_ferbasa.tbcustovariaveladicionado', verbose_name='Custo Var. Adic. CF')),
            ],
            options={
                'verbose_name': '    Custo Variável - Preço',
                'verbose_name_plural': '    Custo Variável - Preços',
                'ordering': ['cus_ite_pre_item'],
            },
        ),
        migrations.CreateModel(
            name='TbDepreAmorti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('dep_recorrente', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('dep_moeda', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('dep_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('dep_fonte', models.FileField(blank=True, null=True, upload_to='fontes', verbose_name='Fonte')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Inicial')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '           Deprec./Amortização',
                'verbose_name_plural': '           Deprec./Amortizações',
                'ordering': ['dep_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbEquacaoAjustePreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equ_aju_pre_descricao', models.CharField(max_length=40, verbose_name='Descrição')),
                ('equ_aju_pre_moeda', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], max_length=3, verbose_name='Moeda do Preço')),
                ('equ_aju_pre_constante_a', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, null=True, verbose_name='A')),
                ('equ_aju_pre_observacao_a', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('equ_aju_pre_constante_b', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, null=True, verbose_name='B')),
                ('equ_aju_pre_observacao_b', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('equ_aju_pre_constante_c', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, null=True, verbose_name='C')),
                ('equ_aju_pre_observacao_c', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('equ_aju_pre_constante_d', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, null=True, verbose_name='D')),
                ('equ_aju_pre_observacao_d', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('equ_aju_pre_constante_e', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, null=True, verbose_name='E')),
                ('equ_aju_pre_observacao_e', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('equ_aju_pre_constante_f', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, null=True, verbose_name='F')),
                ('equ_aju_pre_observacao_f', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('equ_aju_pre_formula', models.CharField(max_length=50, verbose_name='Fórmula')),
                ('equ_aju_pre_primeiro_titulo', models.CharField(blank=True, max_length=6, null=True, verbose_name='Títulos: Primeiro')),
                ('equ_aju_pre_segundo_titulo', models.CharField(blank=True, max_length=6, null=True, verbose_name='Segundo')),
                ('equ_aju_pre_var', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor VAR para teste')),
                ('equ_aju_pre_valor1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='')),
                ('equ_aju_pre_valor2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Equação Ajuste Preço',
                'verbose_name_plural': 'Equações Ajustes Preços',
                'ordering': ['equ_aju_pre_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbFamiliaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_pro_codigo', models.CharField(max_length=35, verbose_name='Família')),
            ],
            options={
                'verbose_name': '  Família de Produto',
                'verbose_name_plural': '  Famílias de Produtos',
                'ordering': ['fam_pro_codigo'],
            },
        ),
        migrations.CreateModel(
            name='TbGrupoCenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gru_cen_codigo', models.CharField(max_length=35, verbose_name='Grupo de Cenários')),
            ],
            options={
                'verbose_name': ' Grupo de Cenários',
                'verbose_name_plural': ' Grupos de Cenários',
                'ordering': ['gru_cen_codigo'],
            },
        ),
        migrations.CreateModel(
            name='TbImpostoRenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_observacao', models.TextField(blank=True, null=True, verbose_name='Imposto de Renda')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=32.0, max_digits=6, verbose_name='Valor Inicial')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': '              Imposto de Renda',
                'verbose_name_plural': '              Imposto de Renda',
            },
        ),
        migrations.CreateModel(
            name='TbIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_nome', models.CharField(max_length=25, verbose_name='Nome')),
                ('ind_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('ind_fonte', models.FileField(blank=True, null=True, upload_to='fontes', verbose_name='Fonte')),
                ('valor_inicial', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='Valor Inicial (%)')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': '                 Indicador',
                'verbose_name_plural': '                 Indicadores',
                'ordering': ['ind_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mer_nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('mer_imagem', models.ImageField(blank=True, null=True, upload_to='tabelas', verbose_name='Imagem')),
                ('mer_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '        Mercado',
                'verbose_name_plural': '        Mercados',
                'ordering': ['mer_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbTaxaDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_observacao', models.TextField(blank=True, null=True, verbose_name='Taxa de Desconto (WACC)')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Valor Inicial')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': '             Taxa de Desconto (WACC)',
                'verbose_name_plural': '             Taxa de Desconto (WACC)',
            },
        ),
        migrations.CreateModel(
            name='TbTipoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('tip_imagem', models.ImageField(blank=True, null=True, upload_to='tabelas', verbose_name='Imagem')),
                ('tip_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '   Tipo de Produção',
                'verbose_name_plural': '   Tipos de Produção',
                'ordering': ['tip_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbUnidadeProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('uni_imagem', models.ImageField(blank=True, null=True, upload_to='tabelas', verbose_name='Imagem')),
                ('uni_localizacao', models.ImageField(blank=True, null=True, upload_to='tabelas', verbose_name='Localização')),
                ('uni_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '         Unidade de Produção',
                'verbose_name_plural': '         Unidades de Produção',
                'ordering': ['uni_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbTaxaDescontoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor (%)')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbtaxadesconto', verbose_name='Taxa de Desconto (WACC)')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Valores Previstos (%)',
                'verbose_name_plural': 'Valores Previstos (%)',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbIndicadoresDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='Valor (%)')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbindicadores', verbose_name='Indicador')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Valores Previstos (%)',
                'verbose_name_plural': 'Valores Previstos (%)',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbImpostoRendaDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor (%)')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbimpostorenda', verbose_name='Imposto de Renda')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Valores Previstos (%)',
                'verbose_name_plural': 'Valores Previstos (%)',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbDepreAmortiDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbdepreamorti', verbose_name='Depreciação/Amortização')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.AddField(
            model_name='tbdepreamorti',
            name='dep_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='tbdepreamorti',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.CreateModel(
            name='TbCustoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_tip_nome', models.CharField(max_length=25, verbose_name='Nome')),
                ('cus_tip_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cus_tip_group', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Grupo(s) Usuários com Permissão')),
            ],
            options={
                'verbose_name': '     Custo Variável - Tipo',
                'verbose_name_plural': '     Custo Variável - Tipos',
                'ordering': ['cus_tip_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbCustoItemPrecoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Preço')),
                ('dau_valor_2', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Inbound')),
                ('dau_valor_3', models.IntegerField(verbose_name='Pagamento (dias)')),
                ('dau_valor_4', models.IntegerField(verbose_name='Pagamento (dias)')),
                ('dau_valor_5', models.IntegerField(verbose_name='Estoque (dias)')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcustoitempreco', verbose_name='Mãe')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.AddField(
            model_name='tbcustoitempreco',
            name='cus_ite_pre_indicador_inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cus_ite_pre_indicador_inbound', to='tabelas.tbindicadores', verbose_name='Indicador do Inbound'),
        ),
        migrations.AddField(
            model_name='tbcustoitempreco',
            name='cus_ite_pre_indicador_preco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cus_ite_pre_indicador_preco', to='tabelas.tbindicadores', verbose_name='Indicador do Preço'),
        ),
        migrations.AddField(
            model_name='tbcustoitempreco',
            name='cus_ite_pre_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcustoitem', verbose_name='Item de Custo'),
        ),
        migrations.AddField(
            model_name='tbcustoitempreco',
            name='cus_ite_pre_unidade_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbunidadeproducao', verbose_name='Unidade de Produção'),
        ),
        migrations.AddField(
            model_name='tbcustoitempreco',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbcustoitem',
            name='cus_ite_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcustotipo', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='TbCustoFixoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('dau_valor_2', models.IntegerField(verbose_name='Pagamento (dias)')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcustofixo', verbose_name='Custo Fixo')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.AddField(
            model_name='tbcustofixo',
            name='fix_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='tbcustofixo',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.CreateModel(
            name='TbCapexDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcapex', verbose_name='Depreciação/Amortização')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.AddField(
            model_name='tbcapex',
            name='cap_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='tbcapex',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.CreateModel(
            name='TbCambioDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcambio', verbose_name='Câmbio')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
    ]
