# Generated by Django 4.2.30 on 2026-09-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcapex',
            name='cap_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='tbcustofixo',
            name='fix_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='tbcustoitempreco',
            name='cus_ite_pre_indicador_inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cus_ite_pre_indicador_inbound', to='tabelas.tbindicadores', verbose_name='Indicador do Inbound'),
        ),
        migrations.AlterField(
            model_name='tbcustoitempreco',
            name='cus_ite_pre_indicador_preco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cus_ite_pre_indicador_preco', to='tabelas.tbindicadores', verbose_name='Indicador do Preço'),
        ),
        migrations.AlterField(
            model_name='tbdepreamorti',
            name='dep_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
    ]
