# Generated by Django 4.2.30 on 2026-09-28 00:56

from django.db import migrations, models
import django.db.models.deletion
import parameters.contexto_usuario


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0003_tbcustoitem_empresa_tbcustotipo_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcustoitem',
            name='cus_ite_tipo',
            field=models.ForeignKey(blank=True, limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcustotipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tbcustoitempreco',
            name='cus_ite_pre_item',
            field=models.ForeignKey(limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcustoitem', verbose_name='Item de Custo'),
        ),
        migrations.AlterField(
            model_name='tbcustoitempreco',
            name='cus_ite_pre_unidade_producao',
            field=models.ForeignKey(limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbunidadeproducao', verbose_name='Unidade de Produção'),
        ),
    ]
