# Generated by Django 4.2.30 on 2026-10-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_alter_tbcustoitem_cus_ite_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtipoproducao',
            name='tip_critério_para_quebra_fluxo',
            field=models.CharField(default='TBD: To Be Defined', max_length=50, verbose_name='Critério Quebra Fluxo'),
            preserve_default=False,
        ),
    ]
