# Generated by Django 4.2.30 on 2026-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0005_tbtipoproducao_tip_critério_para_quebra_fluxo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbtipoproducao',
            old_name='tip_critério_para_quebra_fluxo',
            new_name='tip_criterio_para_quebra_fluxo',
        ),
    ]
