# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbMercadoOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mer_out_moeda', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('mer_out_observacao', models.TextField(blank=True, max_length=80, null=True, verbose_name='Observação')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Inicial')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Custo Outbound',
                'verbose_name_plural': 'Custos Outbound',
                'ordering': ['mer_out_mercado'],
            },
        ),
        migrations.CreateModel(
            name='TbMercadoOutboundDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Valores Previstos',
                'verbose_name_plural': 'Valores Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbProdutoMercadoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_mer_pre_estoque', models.IntegerField(verbose_name='Estoque (dias venda)')),
                ('pro_mer_pre_validado', models.BooleanField(default=0, verbose_name='Validado')),
                ('pro_mer_pre_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pro_mer_pre_moeda', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('pro_mer_pre_outbound', models.BooleanField(default=True, verbose_name='Considerar Outbound (se existir...)')),
                ('pro_mer_pre_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('pro_mer_pre_fonte', models.FileField(blank=True, null=True, upload_to='fontes', verbose_name='Fonte')),
                ('valor_inicial_1', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Volume Mín. Inicial')),
                ('valor_inicial_2', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Volume Máx. Inicial')),
                ('valor_inicial_3', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Preço Inicial')),
                ('valor_inicial_4', models.IntegerField(verbose_name='Pagamento (dias)')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '  Volume/Preço por Mercado',
                'verbose_name_plural': '  Volume/Preços por Mercado',
                'ordering': ['pro_mer_pre_produto', 'pro_mer_pre_mercado'],
            },
        ),
        migrations.CreateModel(
            name='TbProdutoMercadoPrecoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Volume Mínimo')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Volume Máximo')),
                ('dau_valor_3', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Preço')),
                ('dau_valor_4', models.IntegerField(verbose_name='Pagamento (dias)')),
            ],
            options={
                'verbose_name': 'Volume Mín/Máx - Preço Previsto',
                'verbose_name_plural': 'Volumes Mín/Máx - Preços Previstos',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_codigo', models.CharField(max_length=25, verbose_name='Código')),
                ('pro_descricao', models.CharField(max_length=51, verbose_name='Descrição')),
                ('pro_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pro_unidade_producao', models.CharField(choices=[('un', 'un'), ('g', 'g'), ('kg', 'kg'), ('t', 't'), ('h', 'h'), ('hh', 'hh'), ('m3', 'm3'), ('Nm3', 'Nm3'), ('L', 'L'), ('kw', 'kw'), ('kwh', 'kwh'), ('Mwh', 'Mwh')], max_length=3, verbose_name='Unidade')),
                ('pro_imagem', models.ImageField(blank=True, null=True, upload_to='produtos', verbose_name='Imagem')),
                ('pro_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '  Produto',
                'verbose_name_plural': '  Produtos',
                'ordering': ['pro_codigo'],
            },
        ),
    ]
