# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabelas', '0001_initial'),
        ('parameters', '0002_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbprodutos',
            name='pro_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbfamiliaproduto', verbose_name='Família'),
        ),
        migrations.AddField(
            model_name='tbprodutos',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadoprecodaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tbprodutomercadopreco', verbose_name='Produto Mercado Preço'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadoprecodaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_equacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbequacaoajustepreco', verbose_name='Equação de Preço'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_mer_pre_indicador', to='tabelas.tbindicadores', verbose_name='Indicador Preço'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_indicador_vol_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_mer_pre_indicador_vol_max', to='tabelas.tbindicadores', verbose_name='Máx.'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_indicador_vol_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_mer_pre_indicador_vol_min', to='tabelas.tbindicadores', verbose_name='Indicador Volume: Mín.'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbmercado', verbose_name='Mercado'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tbprodutos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbmercadooutbounddaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tbmercadooutbound', verbose_name='Mercado Outbound'),
        ),
        migrations.AddField(
            model_name='tbmercadooutbounddaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbmercadooutbound',
            name='mer_out_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='tbmercadooutbound',
            name='mer_out_mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbmercado', verbose_name='Mercado'),
        ),
        migrations.AddField(
            model_name='tbmercadooutbound',
            name='mer_out_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tbprodutos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='tbmercadooutbound',
            name='mer_out_unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbunidadeproducao', verbose_name='Planta de Produção'),
        ),
        migrations.AddField(
            model_name='tbmercadooutbound',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
    ]
