# Generated by Django 4.1.7 on 2025-01-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbprodutos',
            name='pro_codigo_interno',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cód. Interno'),
        ),
    ]
