# Generated by Django 4.1.7 on 2025-02-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_tbprodutos_pro_codigo_interno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbprodutos',
            name='pro_codigo_interno',
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_codigo_interno',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cód. Interno'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_descricao',
            field=models.CharField(blank=True, max_length=51, null=True, verbose_name='Desc. Interna'),
        ),
    ]
