# Generated by Django 4.1.7 on 2025-02-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_tbprodutos_pro_codigo_interno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbprodutomercadopreco',
            old_name='pro_mer_pre_descricao',
            new_name='pro_mer_pre_descricao_interna',
        ),
    ]
