# Generated by Django 4.2.30 on 2026-09-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0002_alter_tbcapex_cap_indicador_and_more'),
        ('produtos', '0005_rename_pro_mer_pre_descricao_tbprodutomercadopreco_pro_mer_pre_descricao_interna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbmercadooutbound',
            name='mer_out_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pro_mer_pre_indicador', to='tabelas.tbindicadores', verbose_name='Indicador Preço'),
        ),
        migrations.AlterField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_indicador_vol_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pro_mer_pre_indicador_vol_max', to='tabelas.tbindicadores', verbose_name='Máx.'),
        ),
        migrations.AlterField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_indicador_vol_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pro_mer_pre_indicador_vol_min', to='tabelas.tbindicadores', verbose_name='Indicador Volume: Mín.'),
        ),
    ]
