# Generated by Django 4.2.30 on 2026-09-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_alter_tbcustoitem_cus_ite_tipo_and_more'),
        ('produtos', '0007_alter_tbmercadooutbound_mer_out_indicador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbmercadooutbound',
            name='mer_out_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tabelas.tbindicadores', verbose_name='Indicador'),
        ),
    ]
