# Generated by Django 4.2.30 on 2026-10-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_alter_tbcustoitem_cus_ite_tipo_and_more'),
        ('produtos', '0008_alter_tbmercadooutbound_mer_out_indicador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbmercadooutbound',
            name='mer_out_mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbmercado', verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='tbmercadooutbound',
            name='mer_out_unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbunidadeproducao', verbose_name='Planta de Produção'),
        ),
        migrations.AlterField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_equacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbequacaoajustepreco', verbose_name='Equação de Preço'),
        ),
        migrations.AlterField(
            model_name='tbprodutomercadopreco',
            name='pro_mer_pre_mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbmercado', verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='tbprodutos',
            name='pro_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbfamiliaproduto', verbose_name='Família'),
        ),
    ]
