# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbConsumoEspecificoTipoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_esp_tip_pro_descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('con_esp_tip_pro_qtde_produzida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Produzida')),
                ('con_esp_tip_pro_qtde_consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Consumo')),
                ('con_esp_tip_pro_indicador', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Indicador')),
                ('con_esp_tip_pro_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Consumo Específico por Tipo de Produção',
                'verbose_name_plural': ' Consumos Específicos por Tipo de Produção',
                'ordering': ['con_esp_tip_pro_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoComparacaoCenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comparação de Cenários',
                'verbose_name_plural': 'Comparação de Cenários',
                'ordering': ['oti_com_cenario_referencia'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoComparacaoCenariosDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
            ],
            options={
                'verbose_name': 'Análise Comparativa Cenário Ativo - Cenário Referência',
                'verbose_name_plural': 'Análise Comparativa Cenário Ativo - Cenário Referência',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoCustoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Item de Custo/Planta',
                'verbose_name_plural': ' Itens de Custo/Planta',
                'ordering': ['oti_cus_ite_item'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoCustoItemDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Consumo Mínimo')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Consumo Máximo')),
                ('dau_valor_3', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Consumo Calculado')),
                ('dau_valor_4', models.BooleanField(default=False, verbose_name='Ativo')),
                ('dau_valor_5', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Estoque (Qtde)')),
                ('dau_valor_6', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Estoque (Valor)')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
            ],
            options={
                'verbose_name': 'Detalhe ',
                'verbose_name_plural': 'Detalhes',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoEquipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '   Equipamento',
                'verbose_name_plural': '   Equipamentos',
                'ordering': ['oti_equ_equipamento'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoEquipamentosDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.BooleanField(default=True, verbose_name='Running')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Prod.(Volume)')),
                ('dau_valor_3', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Loading Time(h)')),
                ('dau_valor_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Ocupação(%)')),
                ('dau_valor_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Ocupação Mín.(%)')),
                ('dau_valor_7', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Ocupação Máx.(%)')),
                ('dau_valor_6', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Prod.(Horas)')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
            ],
            options={
                'verbose_name': 'Detalhe ',
                'verbose_name_plural': 'Detalhes',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoEquipamentosOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '  Equipamento/Ordem de Produção',
                'verbose_name_plural': '  Equipamentos/Ordem de Produção',
                'ordering': ['oti_equ_ord_equipamento'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoEquipamentosOrdemDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Produção (Volume)')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=0.0, max_digits=9, verbose_name='Produção (Horas)')),
                ('dau_valor_3', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='WIP (Volume)')),
                ('dau_valor_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='WIP (Valor)')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
            ],
            options={
                'verbose_name': 'Detalhe ',
                'verbose_name_plural': 'Detalhes',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '      Produto',
                'verbose_name_plural': '      Produtos',
                'ordering': ['oti_pro_produto'],
            },
        ),
        migrations.CreateModel(
            name='TbOtimizacaoProdutoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Volume Mínimo')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Volume Máximo')),
                ('dau_valor_3', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Vendas')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
            ],
            options={
                'verbose_name': 'Detalhe',
                'verbose_name_plural': 'Detalhes',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbProdutoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '     Produto / Mercado',
                'verbose_name_plural': '     Produtos / Mercados',
                'ordering': ['pro_mer_produto', 'pro_mer_mercado'],
            },
        ),
        migrations.CreateModel(
            name='TbProdutoMercadoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Volume Mínimo')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Volume Máximo')),
                ('dau_valor_3', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Vendas')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
            ],
            options={
                'verbose_name': 'Detalhe',
                'verbose_name_plural': 'Detalhes',
                'ordering': ['dau_order'],
            },
        ),
        migrations.CreateModel(
            name='TbProdutoMercadoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_mer_flu_variavel', models.IntegerField(verbose_name='Variável')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '    Produto / Mercado / Fluxo',
                'verbose_name_plural': '    Produtos / Mercados / Fluxos',
                'ordering': ['pro_mer_flu_variavel'],
            },
        ),
        migrations.CreateModel(
            name='TbProdutoMercadoFluxoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.BooleanField(default=True, verbose_name='Fluxo')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Vendas')),
                ('dau_valor_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Margem Contrib.')),
                ('dau_valor_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Preço')),
                ('dau_valor_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Custo Variável')),
                ('dau_valor_6', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Parcela Outbound')),
                ('dau_valor_7', models.BooleanField(default=True, verbose_name='Equip.')),
                ('dau_valor_8', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Parcela Itens')),
                ('dau_valor_9', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Parcela Inbound')),
                ('dau_valor_10', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Parcela Manutenção')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbprodutomercadofluxo', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Detalhe',
                'verbose_name_plural': 'Detalhes',
                'ordering': ['dau_order'],
            },
        ),
    ]
