# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('otimizacao', '0001_initial'),
        ('fluxos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbprodutomercadofluxodaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadofluxo',
            name='pro_mer_flu_fluxo_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxos.tbfluxoproducao', verbose_name='Fluxo Produção'),
        ),
    ]
