# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otimizacao', '0002_initial'),
        ('tabelas', '0001_initial'),
        ('equipamentos', '0003_initial'),
        ('parameters', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbprodutomercadofluxo',
            name='pro_mer_flu_mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbmercado', verbose_name='Mercado'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadofluxo',
            name='pro_mer_flu_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tbprodutos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadofluxo',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadodaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbprodutomercado', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadodaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbprodutomercado',
            name='pro_mer_mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbmercado', verbose_name='Mercado'),
        ),
        migrations.AddField(
            model_name='tbprodutomercado',
            name='pro_mer_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tbprodutos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='tbprodutomercado',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoprodutodaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbotimizacaoproduto', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoprodutodaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoproduto',
            name='oti_pro_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tbprodutos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoproduto',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoequipamentosordemdaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbotimizacaoequipamentosordem', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoequipamentosordemdaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoequipamentosordem',
            name='oti_equ_ord_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tbequipamentos', verbose_name='Equipamento/Ordem de Produção'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoequipamentosordem',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoequipamentosdaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbotimizacaoequipamentos', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoequipamentosdaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoequipamentos',
            name='oti_equ_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.tbequipamentoscadastro', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoequipamentos',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaocustoitemdaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbotimizacaocustoitem', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbotimizacaocustoitemdaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaocustoitem',
            name='oti_cus_ite_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbcustoitempreco', verbose_name='Item de Custo/Unidade de Produção'),
        ),
        migrations.AddField(
            model_name='tbotimizacaocustoitem',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaocomparacaocenariosdaugther',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbotimizacaocomparacaocenarios', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='tbotimizacaocomparacaocenariosdaugther',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbotimizacaocomparacaocenarios',
            name='oti_com_cenario_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oti_com_cenario_referencia', to='parameters.tbcenarios', verbose_name='Cenário Referência'),
        ),
        migrations.AddField(
            model_name='tbotimizacaocomparacaocenarios',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbcenarios_1', to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecificotipoproducao',
            name='con_esp_tip_pro_consumo_via_equipamento',
            field=models.ManyToManyField(blank=True, related_name='con_esp_tip_pro_consumo_via_equipamento', to='tabelas.tbtipoproducao', verbose_name='Consumo Via Equipamento'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecificotipoproducao',
            name='con_esp_tip_pro_consumo_via_item_consumo',
            field=models.ManyToManyField(blank=True, to='tabelas.tbcustoitem', verbose_name='Consumo Via Item de Consumo'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecificotipoproducao',
            name='con_esp_tip_pro_tipo_producao',
            field=models.ManyToManyField(related_name='con_esp_tip_pro_tipo_producao', to='tabelas.tbtipoproducao', verbose_name='Tipo de Produção'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecificotipoproducao',
            name='tbcenarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário'),
        ),
    ]
