# Generated by Django 4.1.7 on 2023-12-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_initial'),
        ('otimizacao', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbconsumoespecificotipoproducao',
            unique_together={('con_esp_tip_pro_descricao', 'tbcenarios')},
        ),
    ]
