# Generated by Django 4.1.7 on 2025-03-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_alter_tbequipamentosdaugther_dau_valor_3'),
        ('parameters', '0012_alter_tbcenarios_cen_nome'),
        ('otimizacao', '0004_alter_tbconsumoespecificotipoproducao_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbOtimizacaoConjuntoEquipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oti_con_equ_descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('oti_con_equ_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
                ('oti_con_equ_equipamentos', models.ManyToManyField(blank=True, to='equipamentos.tbequipamentoscadastro', verbose_name='Equipamentos')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
        ),
    ]
