# Generated by Django 4.1.7 on 2025-03-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0012_alter_tbcenarios_cen_nome'),
        ('otimizacao', '0005_tbotimizacaoconjuntoequipamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbotimizacaoconjuntoequipamentos',
            options={'ordering': ['oti_con_equ_descricao'], 'verbose_name': '  Equipamento/Conjunto', 'verbose_name_plural': '  Equipamentos/Conjunto'},
        ),
        migrations.CreateModel(
            name='TbOtimizacaoConjuntoEquipamentosDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Produção Mínima')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=999999999, max_digits=9, verbose_name='Produção Máxima')),
                ('dau_valor_3', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Produção')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbotimizacaoconjuntoequipamentos', verbose_name='Mãe')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Produção Mínima e Máxima por Periodo',
                'verbose_name_plural': 'Produções Mínimas e Máximas por Periodo',
                'ordering': ['dau_order'],
            },
        ),
    ]
