# Generated by Django 4.1.7 on 2025-03-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0006_alter_tbotimizacaoconjuntoequipamentos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoconjuntoequipamentosdaugther',
            name='dau_valor_3',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9, null=True, verbose_name='Produção'),
        ),
    ]
