# Generated by Django 4.1.7 on 2025-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0012_alter_tbcenarios_cen_nome'),
        ('otimizacao', '0007_alter_tbotimizacaoconjuntoequipamentosdaugther_dau_valor_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoconjuntoequipamentos',
            name='oti_con_equ_descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='tbotimizacaoconjuntoequipamentos',
            unique_together={('oti_con_equ_descricao', 'tbcenarios')},
        ),
    ]
