# Generated by Django 4.1.7 on 2025-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0008_alter_tbotimizacaoconjuntoequipamentos_oti_con_equ_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoequipamentosdaugther',
            name='dau_ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
