# Generated by Django 4.1.7 on 2025-04-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0009_tbotimizacaoequipamentosdaugther_dau_ativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbotimizacaoequipamentosdaugther',
            name='dau_ativa',
        ),
    ]
