# Generated by Django 4.1.7 on 2025-04-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_alter_tbequipamentosdaugther_dau_valor_3'),
        ('otimizacao', '0010_remove_tbotimizacaoequipamentosdaugther_dau_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoconjuntoequipamentos',
            name='oti_con_equ_equipamentos',
            field=models.ManyToManyField(to='equipamentos.tbequipamentoscadastro', verbose_name='Equipamentos'),
        ),
    ]
