# Generated by Django 4.1.7 on 2025-06-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0011_alter_tbotimizacaoconjuntoequipamentos_oti_con_equ_equipamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbotimizacaoconjuntoequipamentos',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='tbotimizacaoconjuntoequipamentosdaugther',
            name='flag',
        ),
    ]
