# Generated by Django 4.1.7 on 2025-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0012_remove_tbotimizacaoconjuntoequipamentos_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoconjuntoequipamentos',
            name='oti_con_equ_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
