# Generated by Django 4.1.7 on 2025-06-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0029_tbcustovariaveladicionado_cus_var_adi_subproduto_producao_and_more'),
        ('otimizacao', '0015_tbconsumoespecificotipoproducao_con_esp_tip_operacao1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbconsumoespecificotipoproducao',
            name='con_esp_tip_operacao2',
            field=models.CharField(blank=True, choices=[('Multiplicação', 'Multiplicação'), ('Divisão', 'Divisão')], max_length=13, null=True, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecificotipoproducao',
            name='con_esp_tip_pro_ajuste2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_esp_tip_pro_ajuste2', to='custo_ferbasa.tbconsumoespecifico', verbose_name='Indicador Ajuste'),
        ),
    ]
