# Generated by Django 4.1.7 on 2025-06-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0016_tbconsumoespecificotipoproducao_con_esp_tip_operacao2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbconsumoespecificotipoproducao',
            old_name='con_esp_tip_operacao1',
            new_name='con_esp_tip_pro_operacao1',
        ),
        migrations.RenameField(
            model_name='tbconsumoespecificotipoproducao',
            old_name='con_esp_tip_operacao2',
            new_name='con_esp_tip_pro_operacao2',
        ),
    ]
