# Generated by Django 4.1.7 on 2025-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0018_tbconsumoespecificotipoproducao_con_esp_tip_pro_indicador_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbconsumoespecificotipoproducao',
            name='con_esp_tip_pro_descricao',
            field=models.CharField(max_length=90, verbose_name='Descrição'),
        ),
    ]
