# Generated by Django 5.2.4 on 2025-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0024_alter_tbconsumoespecificotipoproducao_con_esp_tip_pro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoprodutodaugther',
            name='dau_valor_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Preço Médio'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoprodutodaugther',
            name='dau_valor_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Custo Var. Médio'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoprodutodaugther',
            name='dau_valor_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Margem Cont. Horária Média'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadodaugther',
            name='dau_valor_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Preço Médio'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadodaugther',
            name='dau_valor_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Custo Var. Médio'),
        ),
        migrations.AddField(
            model_name='tbprodutomercadodaugther',
            name='dau_valor_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Margem Cont. Horária Média'),
        ),
    ]
