# Generated by Django 5.2.4 on 2025-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0025_tbotimizacaoprodutodaugther_dau_valor_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbprodutomercadofluxodaugther',
            name='dau_valor_11',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Margem Horária'),
        ),
    ]
