# Generated by Django 5.2.4 on 2025-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0026_tbprodutomercadofluxodaugther_dau_valor_11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoequipamentosdaugther',
            name='dau_valor_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Loading Time(h)'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoequipamentosdaugther',
            name='dau_valor_6',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Prod.(Horas)'),
        ),
    ]
