# Generated by Django 4.2.30 on 2026-06-28 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0012_alter_tbcenarios_cen_nome'),
        ('otimizacao', '0027_alter_tbotimizacaoequipamentosdaugther_dau_valor_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbOtimizacaoShadow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oti_shadow_restricao', models.CharField(max_length=60, verbose_name='Restrição')),
                ('oti_shadow_tipo', models.CharField(choices=[('E', 'EQUPAMENTO'), ('CE', 'CONJUNTO EQUIPAMENTOS'), ('P', 'PRODUTO'), ('PM', 'PRODUTO/MERCADO'), ('IC', 'ITEM DE CUSTO')], max_length=2, verbose_name='Tipo')),
                ('id_origem', models.IntegerField(blank=True, null=True)),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Sombra da Otimização Simplex',
                'verbose_name_plural': 'Sombras da Otimização Simplex',
            },
        ),
    ]
