# Generated by Django 4.2.30 on 2026-06-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0012_alter_tbcenarios_cen_nome'),
        ('otimizacao', '0028_tbotimizacaoshadow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle'),
        ),
        migrations.CreateModel(
            name='TbOtimizacaoShadowDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(verbose_name='Ano/Mês')),
                ('dau_valor_1', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Sombra Mínimo')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Sombra Máximo')),
                ('dau_valor_3', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Residual Mínimo')),
                ('dau_valor_4', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Residual Máximo')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otimizacao.tbotimizacaoshadow', verbose_name='Mãe')),
                ('tbcenarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Cenário')),
            ],
            options={
                'verbose_name': 'Detalhe',
                'verbose_name_plural': 'Detalhes',
                'ordering': ['dau_order'],
            },
        ),
    ]
