# Generated by Django 4.2.30 on 2026-06-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0029_tbotimizacaoshadow_flag_tbotimizacaoshadowdaugther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='oti_shadow_restricao',
            field=models.CharField(max_length=100, verbose_name='Restrição'),
        ),
    ]
