# Generated by Django 4.2.30 on 2026-06-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0030_alter_tbotimizacaoshadow_oti_shadow_restricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='oti_shadow_id_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id 1'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='oti_shadow_id_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id 2'),
        ),
    ]
