# Generated by Django 4.2.30 on 2026-06-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0031_tbotimizacaoshadow_oti_shadow_id_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano/Mês'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Sombra Mínimo'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Sombra Máximo'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Residual Mínimo'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Residual Máximo'),
        ),
    ]
