# Generated by Django 4.2.30 on 2026-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0032_tbotimizacaoshadow_dau_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbotimizacaoshadow',
            options={'ordering': ['oti_shadow_tipo', 'oti_shadow_restricao', 'dau_order'], 'verbose_name': 'Sombra da Otimização Simplex', 'verbose_name_plural': 'Sombras da Otimização Simplex'},
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_4',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Residual Máximo'),
        ),
        migrations.DeleteModel(
            name='TbOtimizacaoShadowDaugther',
        ),
    ]
