# Generated by Django 4.2.30 on 2026-06-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0033_alter_tbotimizacaoshadow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='TBD'),
        ),
    ]
