# Generated by Django 4.2.30 on 2026-06-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0034_alter_tbotimizacaoshadow_dau_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_5',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Mín'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_6',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Máx'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_7',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Real'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Sombra Mín'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Sombra Máx'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Res. Mín'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_4',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Res. Máx'),
        ),
    ]
