# Generated by Django 4.2.30 on 2026-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0035_tbotimizacaoshadow_dau_valor_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_10',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Lim Inf Máx'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_11',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Lim Máx Máx'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_8',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Lim Inf Mín'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_9',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Lim Máx Mín'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Periodo Order'),
        ),
    ]
