# Generated by Django 4.2.30 on 2026-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0036_tbotimizacaoshadow_dau_valor_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_texto_1',
            field=models.CharField(max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_11',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Lim Sup Máx'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_9',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Lim Sup Mín'),
        ),
    ]
