# Generated by Django 4.2.30 on 2026-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0037_tbotimizacaoshadow_dau_texto_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_10',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True, verbose_name='Lim Inf Máx'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_11',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True, verbose_name='Lim Sup Máx'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_8',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True, verbose_name='Lim Inf Mín'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_valor_9',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True, verbose_name='Lim Sup Mín'),
        ),
    ]
