# Generated by Django 4.2.30 on 2026-07-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0038_alter_tbotimizacaoshadow_dau_valor_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_texto_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rest Conc Mín'),
        ),
        migrations.AddField(
            model_name='tbotimizacaoshadow',
            name='dau_texto_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rest Conc Máx'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_texto_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
