# Generated by Django 4.2.30 on 2026-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0039_tbotimizacaoshadow_dau_texto_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_texto_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rest Conc Mín'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_texto_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rest Conc Máx'),
        ),
    ]
