# Generated by Django 4.2.30 on 2026-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0040_alter_tbotimizacaoshadow_dau_texto_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_texto_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Conc Reduzir'),
        ),
        migrations.AlterField(
            model_name='tbotimizacaoshadow',
            name='dau_texto_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Conc Aumentar'),
        ),
    ]
