# Generated by Django 4.2.30 on 2026-09-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otimizacao', '0041_alter_tbotimizacaoshadow_dau_texto_2_and_more'),
    ]

    operations = [
    ]
