# Generated by Django 4.2.30 on 2026-09-28 00:56

from django.db import migrations, models
import django.db.models.deletion
import parameters.contexto_usuario


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_alter_tbcustoitem_cus_ite_tipo_and_more'),
        ('otimizacao', '0042_auto_20260924_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbprodutomercado',
            name='pro_mer_mercado',
            field=models.ForeignKey(limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbmercado', verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='tbprodutomercadofluxo',
            name='pro_mer_flu_mercado',
            field=models.ForeignKey(limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbmercado', verbose_name='Mercado'),
        ),
    ]
