# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAjusteCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_producao_id', models.IntegerField(verbose_name='Id Item Produção')),
                ('chave', models.TextField(verbose_name='Chave')),
                ('item_consumo_id', models.IntegerField(verbose_name='Id Item Consumo')),
                ('indicador', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Indicador')),
                ('flag', models.BooleanField(blank=True, default=False, verbose_name='Flag')),
                ('ordem_lançamento', models.IntegerField(verbose_name='Ordem Lançamento')),
            ],
        ),
        migrations.CreateModel(
            name='TbAjusteCustoCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_producao_id', models.IntegerField(blank=True, null=True, verbose_name='Id Item Produção')),
                ('chave', models.TextField(blank=True, null=True, verbose_name='Chave')),
                ('item_consumo_id', models.IntegerField(blank=True, null=True, verbose_name='Id Item Consumo')),
                ('indicador', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Indicador')),
                ('flag', models.BooleanField(blank=True, default=False, verbose_name='Flag')),
            ],
        ),
        migrations.CreateModel(
            name='TbCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cen_cus_codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('cen_cus_descricao', models.CharField(max_length=60, verbose_name='Descricao')),
                ('cen_cus_mod', models.IntegerField(default=0, verbose_name='Mão-de-obra Direta (MOD)')),
                ('cen_cus_moi', models.IntegerField(default=0, verbose_name='Mão-de-obra Indireta (MOI)')),
                ('cen_cus_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '      Centro de Custo',
                'verbose_name_plural': '      Centros de Custo',
                'ordering': ['cen_cus_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbConsumoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_esp_descricao', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
                ('con_esp_validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('con_esp_area_responsavel', models.CharField(choices=[('MET', 'METALURGIA'), ('MIN', 'MINERAÇÃO'), ('FLO', 'FLORESTAL')], max_length=3, verbose_name='Área Responsável')),
                ('con_esp_ano_mes_inicio', models.CharField(max_length=7, verbose_name='Ano/Mês Início')),
                ('con_esp_ano_mes_fim', models.CharField(max_length=7, verbose_name='Ano/Mês Fim')),
                ('con_esp_status', models.CharField(default='CALCULADO', max_length=20, verbose_name='Status')),
                ('con_esp_desvio_producao', models.BooleanField(default=True, verbose_name='Considerar desvio como produção (devem ser selecionados em Itens de Consumo escolhidos(s))')),
                ('con_esp_qtde_produzida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Produzida')),
                ('con_esp_qtde_consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Consumo')),
                ('con_esp_indicador', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Indicador')),
                ('con_esp_equacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Equação Cons. Específico')),
                ('con_esp_tipo_equacao', models.CharField(blank=True, choices=[('SOM', 'SOMA'), ('MUL', 'MULTIPLICAÇÃO')], default='SOM', max_length=3, null=True, verbose_name='Tipo Equação')),
                ('con_esp_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '  Consumo Específico SPS',
                'verbose_name_plural': '  Consumos Específicos SPS',
                'ordering': ['con_esp_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_con_codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('con_con_descricao', models.CharField(max_length=60, verbose_name='Descricao')),
                ('con_con_pessoal', models.BooleanField(default=False, verbose_name='Conta de Pessoal')),
                ('con_con_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '       Conta Contábil',
                'verbose_name_plural': '       Contas Contábeis',
                'ordering': ['con_con_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbCustoVariavelAdicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_var_adi_descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cus_var_adi_validado', models.BooleanField(default=0, verbose_name='Validado')),
                ('cus_var_adi_ano_mes_inicio', models.CharField(max_length=7, verbose_name='Ano/Mês Início')),
                ('cus_var_adi_ano_mes_fim', models.CharField(max_length=7, verbose_name='Ano/Mês Fim')),
                ('cus_var_adi_status', models.CharField(default='CALCULADO', max_length=20, verbose_name='Status')),
                ('cus_var_adi_qtde_produzida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Produzida')),
                ('cus_var_adi_custo_variavel_adicionado_material', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. Material')),
                ('cus_var_adi_custo_variavel_adicionado_ggf', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. GGF')),
                ('cus_var_adi_custo_variavel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Variável')),
                ('cus_var_adi_custo_fixo_outros', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros')),
                ('cus_var_adi_custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total')),
                ('cus_var_adi_custo_variavel_ggf_direto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Direto')),
                ('cus_var_adi_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': ' Custo Variável Adicionado SPS',
                'verbose_name_plural': ' Custos Variáveis Adicionados SPS',
                'ordering': ['cus_var_adi_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbEstabelecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_codigo', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('est_nome', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('est_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '         Estabelecimento',
                'verbose_name_plural': '         Estabelecimentos',
                'ordering': ['est_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbGruposMaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gru_maq_codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('gru_maq_nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('gru_maq_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '        Grupo Máquina',
                'verbose_name_plural': '        Grupos Máquinas',
                'ordering': ['gru_maq_codigo'],
            },
        ),
        migrations.CreateModel(
            name='TbItensConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ite_con_codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('ite_con_descricao', models.CharField(max_length=60, verbose_name='Descrição')),
                ('ite_con_unidade', models.CharField(max_length=2, verbose_name='Unidade')),
                ('ite_con_tipo', models.CharField(choices=[('COMPRADO', 'COMPRADO'), ('FABRICADO', 'FABRICADO')], max_length=9, verbose_name='Tipo')),
                ('ite_subproduto', models.BooleanField(default=False, verbose_name='Subproduto')),
                ('ite_con_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '          Item de Consumo',
                'verbose_name_plural': '          Itens de Consumo',
                'ordering': ['ite_con_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbItensProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ite_pro_codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('ite_pro_descricao', models.CharField(max_length=60, verbose_name='Descrição')),
                ('ite_pro_unidade', models.CharField(max_length=2, verbose_name='Unidade')),
                ('ite_pro_ano_mes_inicio', models.CharField(blank=True, max_length=7, null=True, verbose_name='Ano/Mês Início')),
                ('ite_pro_ano_mes_fim', models.CharField(blank=True, max_length=7, null=True, verbose_name='Ano/Mês Fim')),
                ('ite_pro_qtde_produzida_real', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Qtde Produzida Real')),
                ('ite_pro_qtde_produzida_vazio', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Qtde Produzida Mov./Ext.')),
                ('ite_pro_percentual_variavel_ggf', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Perc. Variável GGF (%)')),
                ('ite_pro_percentual_fixo_outros_ggf', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Perc. Fixo/Outros GGF (%)')),
                ('ite_pro_ggf_variavel_direto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor GGF Variável Direto')),
                ('ite_pro_ggf_fixo_outros_direto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor GGF Fixo/Outros Direto')),
                ('ite_pro_ggf_variavel_pi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor GGF Variável Prod. Internos')),
                ('ite_pro_ggf_fixo_outros_pi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor GGF Fixo/Outros Prod. Internos')),
                ('ite_pro_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '           Item de Produção',
                'verbose_name_plural': '           Itens de Produção',
                'ordering': ['ite_pro_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbItensProducaoDaugther1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.TextField(blank=True, null=True, verbose_name='Chave')),
                ('indicador', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Indicador')),
                ('item_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbitensconsumo', verbose_name='Item de Consumo')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbitensproducao', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Arvore Genealógica de Produção',
                'verbose_name_plural': 'Arvore Genealógica de Produção',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='TbItensProducaoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Quantidade Consumida')),
                ('valor_material', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Material')),
                ('valor_ggf', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor GGF')),
                ('item_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbitensconsumo', verbose_name='Item Consumo')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbitensproducao', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': '          Item de Consumo',
                'verbose_name_plural': '          Itens de Consumo',
                'ordering': ['item_consumo'],
            },
        ),
        migrations.CreateModel(
            name='TbCustoVariavelAdicionadoDaugther1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('consumo_especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbconsumoespecifico', verbose_name='Consumo Específico')),
                ('custo_variavel_adicionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbcustovariaveladicionado', verbose_name='Custo Variável Adicionado')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mae', to='custo_ferbasa.tbcustovariaveladicionado', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Custo Variável Adicional',
                'verbose_name_plural': 'Custos Variáveis Adicionais',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TbCustoVariavelAdicionadoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=7, verbose_name='Ano/Mês')),
                ('qtde_produzida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtde Produzida')),
                ('custo_variavel_adicionado_material', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custo Var. Adic. Material')),
                ('custo_variavel_adicionado_ggf', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custo Var. Adic. GGF')),
                ('custo_variavel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Varíável')),
                ('custo_fixo_outros', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total')),
                ('custo_variavel_ggf_direto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custo Var. GGF Direto')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbcustovariaveladicionado', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Valor Histórico',
                'verbose_name_plural': 'Valores Históricos',
                'ordering': ['ano_mes'],
            },
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_grupo_maquina',
            field=models.ManyToManyField(blank=True, to='custo_ferbasa.tbgruposmaquinas', verbose_name='Grupos Máquina'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_item_consumo',
            field=models.ManyToManyField(blank=True, to='custo_ferbasa.tbitensconsumo', verbose_name='Itens de Consumo para Desconsiderar'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_item_producao',
            field=models.ManyToManyField(to='custo_ferbasa.tbitensproducao', verbose_name='Itens de Produção'),
        ),
        migrations.CreateModel(
            name='TbContaContabilCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_con_cen_cus_descricao', models.CharField(max_length=80, verbose_name='Descricao')),
                ('con_con_cen_cus_tipo', models.CharField(choices=[('V', 'VARIÁVEL'), ('F', 'FIXO'), ('O', 'OUTRO'), ('A', 'AGUARDANDO')], max_length=8, verbose_name='Tipo')),
                ('con_con_cen_cus_percentual', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Percentual (%)')),
                ('con_con_cen_cus_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('con_con_cen_cus_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbcentrocusto', verbose_name='Centro de Custo')),
                ('con_con_cen_cus_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbcontacontabil', verbose_name='Conta Contábil')),
                ('con_con_cen_cus_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbestabelecimentos', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': '     Conta Contábil/Centro de Custo',
                'verbose_name_plural': '     Contas Contábeis/Centros de Custo',
                'ordering': ['con_con_cen_cus_descricao'],
                'unique_together': {('con_con_cen_cus_conta', 'con_con_cen_cus_cc', 'con_con_cen_cus_estabelecimento')},
            },
        ),
        migrations.CreateModel(
            name='TbConsumoEspecificoDaugther1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('consumo_especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbconsumoespecifico', verbose_name='Consumo Específico')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mae', to='custo_ferbasa.tbconsumoespecifico', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Consumo Específico Complementar',
                'verbose_name_plural': 'Consumos Específicos Complementares',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TbConsumoEspecificoDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=7, verbose_name='Ano/Mês')),
                ('qtde_produzida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtde Produzida')),
                ('qtde_consumo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtde Consumo')),
                ('indicador', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Indicador')),
                ('flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbconsumoespecifico', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Valor Histórico',
                'verbose_name_plural': 'Valores Históricos',
                'ordering': ['ano_mes'],
            },
        ),
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_grupo_maquina',
            field=models.ManyToManyField(blank=True, to='custo_ferbasa.tbgruposmaquinas', verbose_name='Grupos Máquina'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_item_consumo',
            field=models.ManyToManyField(blank=True, to='custo_ferbasa.tbitensconsumo', verbose_name='Itens de Consumo'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_item_producao',
            field=models.ManyToManyField(to='custo_ferbasa.tbitensproducao', verbose_name='Itens de Produção'),
        ),
        migrations.CreateModel(
            name='TbProducaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_men_ano_mes', models.CharField(max_length=7, verbose_name='Ano/Mês')),
                ('pro_men_ordem_producao', models.CharField(max_length=9, verbose_name='Ordem Produção')),
                ('pro_men_qtde_produzida', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Qtde Produzida')),
                ('pro_men_qtde_consumo', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Qtde Consumo')),
                ('pro_men_valor_material', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Material')),
                ('pro_men_valor_ggf', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor GGF')),
                ('pro_men_valor_ultima_entrada', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Última Entrada')),
                ('pro_men_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('pro_men_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbestabelecimentos', verbose_name='Estabelecimento')),
                ('pro_men_grupo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbgruposmaquinas', verbose_name='Grupo Máquina')),
                ('pro_men_item_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbitensconsumo', verbose_name='Item Consumo')),
                ('pro_men_item_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbitensproducao', verbose_name='Item Produção')),
            ],
            options={
                'verbose_name': '    Produção Mensal',
                'verbose_name_plural': '    Produção Mensal',
                'ordering': ['pro_men_ano_mes', 'pro_men_item_producao'],
                'unique_together': {('pro_men_ano_mes', 'pro_men_estabelecimento', 'pro_men_grupo_maquina', 'pro_men_ordem_producao', 'pro_men_item_producao', 'pro_men_item_consumo')},
            },
        ),
        migrations.CreateModel(
            name='TbDistribuicaoGGFMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_ggf_men_ano_mes', models.CharField(max_length=7, verbose_name='Ano/Mês')),
                ('dis_ggf_men_ordem_producao', models.CharField(max_length=9, verbose_name='Ordem Produção')),
                ('dis_ggf_men_qtde_produzida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtde Produzida')),
                ('dis_ggf_men_valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('dis_ggf_men_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('dis_ggf_men_conta_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbcontacontabilcentrocusto', verbose_name='Conta Contábil/Centro de Custo')),
                ('dis_ggf_men_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbestabelecimentos', verbose_name='Estabelecimento')),
                ('dis_ggf_men_grupo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbgruposmaquinas', verbose_name='Grupo Máquina')),
                ('dis_ggf_men_item_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbitensproducao', verbose_name='Item Produção')),
            ],
            options={
                'verbose_name': '   Distribuição GGF Mensal',
                'verbose_name_plural': '   Distribuição GGF Mensal',
                'ordering': ['dis_ggf_men_ano_mes', 'dis_ggf_men_item_producao'],
                'unique_together': {('dis_ggf_men_ano_mes', 'dis_ggf_men_estabelecimento', 'dis_ggf_men_grupo_maquina', 'dis_ggf_men_ordem_producao', 'dis_ggf_men_item_producao', 'dis_ggf_men_conta_cc')},
            },
        ),
    ]
