# Generated by Django 4.1.7 on 2024-01-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbRegressaoLinearMultipla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_lin_mul_descricao', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
                ('reg_lin_mul_ano_mes_inicio', models.CharField(max_length=7, verbose_name='Ano/Mês Início')),
                ('reg_lin_mul_ano_mes_fim', models.CharField(max_length=7, verbose_name='Ano/Mês Fim')),
                ('reg_lin_mul_status', models.TextField(blank=True, null=True, verbose_name='Status')),
                ('reg_lin_mul_equacao_regressao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equação Regressão')),
                ('reg_lin_mul_r2_regressao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='R2 Regressão')),
                ('reg_lin_mul_desvio_producao', models.BooleanField(default=True, verbose_name='Considerar desvio como produção')),
                ('reg_lin_mul_qtde_produzida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Produzida')),
                ('reg_lin_mul_sumario', models.TextField(blank=True, null=True, verbose_name='Sumário')),
                ('reg_lin_mul_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('reg_lin_mul_grupo_maquina', models.ManyToManyField(blank=True, to='custo_ferbasa.tbgruposmaquinas', verbose_name='Grupos Máquina')),
                ('reg_lin_mul_item_producao', models.ManyToManyField(to='custo_ferbasa.tbitensproducao', verbose_name='Itens de Produção')),
            ],
            options={
                'verbose_name': 'Regressão Linear Múltipla',
                'verbose_name_plural': 'Regressões Lineares Múltiplas',
                'ordering': ['reg_lin_mul_descricao'],
            },
        ),
        migrations.CreateModel(
            name='TbRegressaoLinearMultiplaDaugther1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=7, verbose_name='Ano/Mês')),
                ('variavel', models.CharField(max_length=5, verbose_name='Variável')),
                ('itens_consumo', models.TextField(blank=True, null=True, verbose_name='Itens Consumo')),
                ('qtde_produzida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtde Produzida')),
                ('qtde_consumo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtde Consumo')),
                ('indicador', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Indicador')),
                ('flag', models.BooleanField(default=False, verbose_name='Controle')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbregressaolinearmultipla', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Base de Dados',
                'verbose_name_plural': 'Base de Dados',
                'ordering': ['ano_mes', '-variavel'],
            },
        ),
        migrations.CreateModel(
            name='TbRegressaoLinearMultiplaDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(default='CONSUMO', max_length=10, verbose_name='Classificação')),
                ('indicador', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Indicador')),
                ('minimo', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Mínimo')),
                ('media', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Média')),
                ('maximo', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Máximo')),
                ('tipo_variavel', models.CharField(blank=True, choices=[('Y', 'DEPENDENTE(Y)'), ('X', 'INDEPENDENTE(X)'), ('D', 'DESCONSIDERAR(D)')], default='D', max_length=3, null=True, verbose_name='Tipo Variável')),
                ('agrupamento', models.IntegerField(blank=True, null=True, verbose_name='Agrupamento')),
                ('coeficiente', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Coeficiente')),
                ('pt', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='P>|t|')),
                ('flag', models.BooleanField(default=False, verbose_name='Controle')),
                ('item_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbitensconsumo', verbose_name='Item de Consumo / Código')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbregressaolinearmultipla', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Variável',
                'verbose_name_plural': 'Variáveis',
                'ordering': ['-tipo_variavel', 'agrupamento', 'item_consumo'],
            },
        ),
    ]
