# Generated by Django 4.1.7 on 2024-01-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0002_tbregressaolinearmultipla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbregressaolinearmultipla',
            name='reg_lin_mul_status_segundo_plano',
            field=models.CharField(default='CALCULADO', max_length=20, verbose_name='Status Segundo Plano'),
        ),
    ]
