# Generated by Django 4.1.7 on 2024-01-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0003_tbregressaolinearmultipla_reg_lin_mul_status_segundo_plano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbregressaolinearmultipla',
            name='reg_lin_mul_status_segundo_plano',
        ),
        migrations.AlterField(
            model_name='tbregressaolinearmultipla',
            name='reg_lin_mul_status',
            field=models.TextField(blank=True, default='CALCULANDO', null=True, verbose_name='Status'),
        ),
    ]
