# Generated by Django 4.1.7 on 2024-01-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0004_remove_tbregressaolinearmultipla_reg_lin_mul_status_segundo_plano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbregressaolinearmultipladaugther',
            name='tipo_variavel',
            field=models.CharField(choices=[('Y', 'DEPENDENTE(Y)'), ('X', 'INDEPENDENTE(X)'), ('D', 'DESCONSIDERAR(D)')], default='D', max_length=3, verbose_name='Tipo Variável'),
        ),
    ]
