# Generated by Django 4.1.7 on 2024-06-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0005_alter_tbregressaolinearmultipladaugther_tipo_variavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle'),
        ),
        migrations.AlterField(
            model_name='tbconsumoespecifico',
            name='con_esp_desvio_producao',
            field=models.BooleanField(default=True, verbose_name='Considerar desvio como produção (devem ser selecionados em Itens de Consumo escolhidos(s)'),
        ),
    ]
