# Generated by Django 4.1.7 on 2024-06-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0006_tbconsumoespecifico_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Controle'),
        ),
    ]
