# Generated by Django 4.1.7 on 2025-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0007_tbcustovariaveladicionado_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_ajustar_periodo',
            field=models.BooleanField(default=True, verbose_name='Ajustar Período Prod. Mínima'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_producao_minima',
            field=models.DecimalField(blank=True, decimal_places=0, default=1000, max_digits=10, null=True, verbose_name='Prod. Minima'),
        ),
    ]
