# Generated by Django 4.1.7 on 2025-01-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0008_tbconsumoespecifico_con_esp_ajustar_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbconsumoespecifico',
            name='con_esp_ajustar_periodo',
            field=models.BooleanField(default=True, verbose_name='Ajustar Período Pela Prod. Mínima'),
        ),
    ]
