# Generated by Django 4.1.7 on 2025-01-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0009_alter_tbconsumoespecifico_con_esp_ajustar_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_ajustar_periodo',
            field=models.BooleanField(default=True, verbose_name='Ajustar Período Pela Prod. Mínima'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_producao_minima',
            field=models.DecimalField(blank=True, decimal_places=0, default=1000, max_digits=10, null=True, verbose_name='Prod. Minima'),
        ),
    ]
