# Generated by Django 4.1.7 on 2025-02-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0011_tbconsumoespecifico_con_esp_alterado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbconsumoespecifico',
            name='con_esp_alterado_por',
        ),
        migrations.RemoveField(
            model_name='tbconsumoespecifico',
            name='con_esp_compartilhar',
        ),
        migrations.RemoveField(
            model_name='tbconsumoespecifico',
            name='con_esp_criado_por',
        ),
    ]
