# Generated by Django 4.1.7 on 2025-02-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0012_remove_tbconsumoespecifico_con_esp_alterado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_alterado_por',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_compartilhar',
            field=models.BooleanField(default=False, verbose_name='Compartilhar'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_criado_por',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Criado por'),
        ),
    ]
