# Generated by Django 4.1.7 on 2025-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0014_tbcustovariaveladicionado_cus_var_adi_qtde_desviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='qtde_desviada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtde Desviada'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='qtde_produzida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtde Produzida'),
        ),
    ]
