# Generated by Django 4.1.7 on 2025-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0016_alter_tbcustovariaveladicionadodaugther_qtde_desviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_fixo_outros_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (Desv)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_total_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (Desv)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Variável (Desv)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_ggf_direto_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Direto (Desv)'),
        ),
    ]
