# Generated by Django 4.1.7 on 2025-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0017_tbcustovariaveladicionado_cus_var_adi_custo_fixo_outros_desv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_fixo_outros_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (D)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_total_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (D)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Varíável (D)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_ggf_direto_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Direto (D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_fixo_outros_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_total_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Variável (D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_ggf_direto_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Direto (D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_ggf_direto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Direto'),
        ),
    ]
