# Generated by Django 4.1.7 on 2025-02-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0018_tbcustovariaveladicionadodaugther_custo_fixo_outros_desv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='con_esp_qtde_desviada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Desviada'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_fixo_outros_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (D=0)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_total_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (D=0)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Variável (D=0)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_ggf_direto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_ggf_direto_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (D=0)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_fixo_outros_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (D=0)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_total_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (D=0)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Varíável (D=0)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_ggf_direto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_ggf_direto_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (D=0)'),
        ),
    ]
