# Generated by Django 4.1.7 on 2025-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0019_tbconsumoespecifico_con_esp_qtde_desviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbconsumoespecificodaugther',
            name='qtde_desviada',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Desviada'),
        ),
        migrations.AlterField(
            model_name='tbconsumoespecificodaugther',
            name='qtde_produzida',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Qtde Produzida'),
        ),
    ]
