# Generated by Django 4.1.7 on 2025-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0020_tbconsumoespecificodaugther_qtde_desviada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbconsumoespecifico',
            name='con_esp_indicador',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Indicador (SPS)'),
        ),
        migrations.AlterField(
            model_name='tbconsumoespecificodaugther',
            name='indicador',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Indicador (SPS)'),
        ),
    ]
