# Generated by Django 4.1.7 on 2025-02-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0021_alter_tbconsumoespecifico_con_esp_indicador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='flag1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Controle'),
        ),
    ]
