# Generated by Django 4.1.7 on 2025-02-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0022_tbconsumoespecifico_flag1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbconsumoespecifico',
            name='flag1',
        ),
    ]
