# Generated by Django 4.1.7 on 2025-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0023_remove_tbconsumoespecifico_flag1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_desvio_producao',
            field=models.BooleanField(default=True, verbose_name='Considerar Desvio como Produção'),
        ),
        migrations.AlterField(
            model_name='tbconsumoespecifico',
            name='con_esp_desvio_producao',
            field=models.BooleanField(default=True, verbose_name='Considerar Desvio como Produção'),
        ),
        migrations.AlterField(
            model_name='tbconsumoespecifico',
            name='con_esp_indicador',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='<b style="color:blue;">Indicador (SPS)</b>'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_fixo_outros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (D=P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (D=P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Variável (D=P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_ggf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. GGF (SPS)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_material',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. Mat. (SPS)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_ggf_direto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (D=P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_ggf',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custo Var. Adic. GGF (SPS)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_material',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custo Var. Adic. Mat. (SPS)'),
        ),
    ]
