# Generated by Django 4.1.7 on 2025-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0024_tbcustovariaveladicionado_cus_var_adi_desvio_producao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_ggf_p',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. GGF (P)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_ggf_p_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. GGF (P+D)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_material_p',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. Mat. (P)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_material_p_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. Mat. (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_fixo_outros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_fixo_outros_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_total_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Variável (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Variável (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_ggf_direto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_ggf_direto_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_fixo_outros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_fixo_outros_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_total_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Varíável (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_ggf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. GGF (SPS)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. Mat. (SPS)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Varíável (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_ggf_direto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_ggf_direto_desv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (P+D)'),
        ),
    ]
