# Generated by Django 4.1.7 on 2025-02-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0025_tbcustovariaveladicionadodaugther_custo_variavel_adicionado_ggf_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_ggf_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. GGF (P)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_ggf_p_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. GGF (P+D)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_material_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. Mat. (P)'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_material_p_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. Mat. (P+D)'),
        ),
    ]
