# Generated by Django 4.1.7 on 2025-02-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0026_tbcustovariaveladicionado_cus_var_adi_custo_variavel_adicionado_ggf_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_material',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. Mat (SPS)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_material_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. Mat (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_custo_variavel_adicionado_material_p_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Var. Adic. Mat (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. Mat (SPS)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_material_p',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. Mat (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_adicionado_material_p_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Var. Adic. Mat (P+D)'),
        ),
    ]
