# Generated by Django 4.1.7 on 2025-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0027_alter_tbcustovariaveladicionado_cus_var_adi_custo_variavel_adicionado_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbconsumoespecifico',
            name='con_esp_desvio_producao',
            field=models.BooleanField(default=True, verbose_name='Considerar Desvio como Produção (D+P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_fixo_outros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_fixo_outros_desv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Custo Fixo/Outros (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Custo Total (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_total_desv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Custo Total (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Custo Varíável (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_desv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Custo Varíável (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_ggf_direto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (P)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionadodaugther',
            name='custo_variavel_ggf_direto_desv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Custo Var. GGF Fase (P+D)'),
        ),
    ]
