# Generated by Django 4.1.7 on 2025-03-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0028_alter_tbconsumoespecifico_con_esp_desvio_producao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_subproduto_producao',
            field=models.BooleanField(default=False, verbose_name='Considerar Subproduto como Produção (Quando Escolhido)'),
        ),
        migrations.AlterField(
            model_name='tbconsumoespecifico',
            name='con_esp_desvio_producao',
            field=models.BooleanField(default=True, verbose_name='Considerar Desvio como Produção (P+D)'),
        ),
        migrations.AlterField(
            model_name='tbcustovariaveladicionado',
            name='cus_var_adi_desvio_producao',
            field=models.BooleanField(default=True, verbose_name='Considerar Desvio como Produção (P+D)'),
        ),
    ]
