# Generated by Django 5.2.4 on 2026-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0029_tbcustovariaveladicionado_cus_var_adi_subproduto_producao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcentrocusto',
            name='cen_cus_codigo_novo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Código Novo'),
        ),
        migrations.AddField(
            model_name='tbcentrocusto',
            name='cen_cus_descricao_nova',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Descricao Nova'),
        ),
    ]
