# Generated by Django 5.2.4 on 2026-03-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0030_tbcentrocusto_cen_cus_codigo_novo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcentrocusto',
            name='cen_cus_codigo_novo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código Novo'),
        ),
    ]
