# Generated by Django 5.2.4 on 2026-03-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0031_alter_tbcentrocusto_cen_cus_codigo_novo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCentroCusto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cen_cus_codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('cen_cus_descricao', models.CharField(max_length=60, verbose_name='Descricao')),
                ('cen_cus_mod', models.IntegerField(default=0, verbose_name='Mão-de-obra Direta (MOD)')),
                ('cen_cus_moi', models.IntegerField(default=0, verbose_name='Mão-de-obra Indireta (MOI)')),
                ('cen_cus_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': '      Centro de Custo/2026->',
                'verbose_name_plural': '      Centros de Custo/2026->',
                'ordering': ['cen_cus_descricao'],
            },
        ),
        migrations.AlterModelOptions(
            name='tbcentrocusto',
            options={'ordering': ['cen_cus_descricao'], 'verbose_name': '      Centro de Custo/2019-2025', 'verbose_name_plural': '      Centros de Custo/2019-2025'},
        ),
        migrations.AlterModelOptions(
            name='tbcontacontabilcentrocusto',
            options={'ordering': ['con_con_cen_cus_descricao'], 'verbose_name': '     Conta Contábil/Centro de Custo/2019-2025', 'verbose_name_plural': '     Contas Contábeis/Centros de Custo/2019-2025'},
        ),
        migrations.RemoveField(
            model_name='tbcentrocusto',
            name='cen_cus_codigo_novo',
        ),
        migrations.RemoveField(
            model_name='tbcentrocusto',
            name='cen_cus_descricao_nova',
        ),
        migrations.CreateModel(
            name='TbContaContabilCentroCusto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_con_cen_cus_descricao', models.CharField(max_length=80, verbose_name='Descricao')),
                ('con_con_cen_cus_tipo', models.CharField(choices=[('V', 'VARIÁVEL'), ('F', 'FIXO'), ('O', 'OUTRO'), ('A', 'AGUARDANDO')], max_length=8, verbose_name='Tipo')),
                ('con_con_cen_cus_percentual', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Percentual (%)')),
                ('con_con_cen_cus_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('con_con_cen_cus_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbcentrocusto', verbose_name='Centro de Custo')),
                ('con_con_cen_cus_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbcontacontabil', verbose_name='Conta Contábil')),
                ('con_con_cen_cus_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custo_ferbasa.tbestabelecimentos', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': '     Conta Contábil/Centro de Custo/2026->',
                'verbose_name_plural': '     Contas Contábeis/Centros de Custo/2026->',
                'ordering': ['con_con_cen_cus_descricao'],
                'unique_together': {('con_con_cen_cus_conta', 'con_con_cen_cus_cc', 'con_con_cen_cus_estabelecimento')},
            },
        ),
    ]
