# Generated by Django 5.2.4 on 2026-03-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0032_tbcentrocusto1_alter_tbcentrocusto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbCentroCusto1',
        ),
        migrations.AlterModelOptions(
            name='tbcentrocusto',
            options={'ordering': ['cen_cus_descricao'], 'verbose_name': '      Centro de Custo', 'verbose_name_plural': '      Centros de Custo'},
        ),
        migrations.AddField(
            model_name='tbcentrocusto',
            name='cen_cus_referencia',
            field=models.CharField(choices=[('1', '<--2025'), ('2', '2026-->')], default=1, max_length=1, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbcentrocusto',
            name='cen_cus_codigo',
            field=models.CharField(max_length=6, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='tbcentrocusto',
            unique_together={('cen_cus_codigo', 'cen_cus_referencia')},
        ),
        migrations.DeleteModel(
            name='TbContaContabilCentroCusto1',
        ),
    ]
