# Generated by Django 5.2.4 on 2026-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_ferbasa', '0033_delete_tbcentrocusto1_alter_tbcentrocusto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbcontacontabilcentrocusto',
            options={'verbose_name': '     Conta Contábil/Centro de Custo', 'verbose_name_plural': '     Contas Contábeis/Centros de Custo'},
        ),
        migrations.RemoveField(
            model_name='tbcontacontabilcentrocusto',
            name='con_con_cen_cus_descricao',
        ),
        migrations.AlterField(
            model_name='tbcentrocusto',
            name='cen_cus_referencia',
            field=models.CharField(choices=[('1', '<--2025'), ('2', '2026-->')], max_length=1, verbose_name='Referência'),
        ),
    ]
