# Generated by Django 4.2.30 on 2026-09-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0027_relatoriopdf_empresa'),
        ('custo_ferbasa', '0034_alter_tbcontacontabilcentrocusto_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbcentrocusto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tbajustecusto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbajustecustocopy',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbcentrocusto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecifico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecificodaugther',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbconsumoespecificodaugther1',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbcontacontabil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbcontacontabilcentrocusto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbcustovariaveladicionadodaugther1',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbdistribuicaoggfmensal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbestabelecimentos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbgruposmaquinas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbitensconsumo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbitensproducao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbitensproducaodaugther',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbitensproducaodaugther1',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbproducaomensal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbregressaolinearmultipla',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbregressaolinearmultipladaugther',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbregressaolinearmultipladaugther1',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tbconsumoespecifico',
            name='con_esp_descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tbcontacontabil',
            name='con_con_codigo',
            field=models.CharField(max_length=6, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tbestabelecimentos',
            name='est_codigo',
            field=models.CharField(max_length=3, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tbestabelecimentos',
            name='est_nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tbgruposmaquinas',
            name='gru_maq_codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tbitensconsumo',
            name='ite_con_codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tbitensproducao',
            name='ite_pro_codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tbregressaolinearmultipla',
            name='reg_lin_mul_descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='tbcentrocusto',
            unique_together={('cen_cus_codigo', 'cen_cus_referencia', 'empresa')},
        ),
        migrations.AddConstraint(
            model_name='tbconsumoespecifico',
            constraint=models.UniqueConstraint(fields=('con_esp_descricao', 'empresa'), name='consumoespecifico_descricao_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tbcontacontabil',
            constraint=models.UniqueConstraint(fields=('con_con_codigo', 'empresa'), name='contacontabil_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tbestabelecimentos',
            constraint=models.UniqueConstraint(fields=('est_codigo', 'empresa'), name='estabelecimento_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tbestabelecimentos',
            constraint=models.UniqueConstraint(fields=('est_nome', 'empresa'), name='estabelecimento_nome_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tbgruposmaquinas',
            constraint=models.UniqueConstraint(fields=('gru_maq_codigo', 'empresa'), name='grupomaquina_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tbitensconsumo',
            constraint=models.UniqueConstraint(fields=('ite_con_codigo', 'empresa'), name='itemconsumo_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tbitensproducao',
            constraint=models.UniqueConstraint(fields=('ite_pro_codigo', 'empresa'), name='itemproducao_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tbregressaolinearmultipla',
            constraint=models.UniqueConstraint(fields=('reg_lin_mul_descricao', 'empresa'), name='regressao_descricao_unica_por_empresa'),
        ),
    ]
