# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cen_nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('cen_descricao', models.TextField(null=True, verbose_name='Descrição')),
                ('cen_tipo', models.CharField(choices=[('Mensal', 'Mensal'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual')], max_length=10, verbose_name='Tipo')),
                ('cen_inicio', models.CharField(default='2021/01', max_length=7, verbose_name='Início')),
                ('cen_fim', models.CharField(default='2021/12', max_length=7, verbose_name='Fim')),
                ('cen_ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('flag', models.IntegerField(blank=True, null=True, verbose_name='Controle')),
                ('cen_copiar_de', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='parameters.tbcenarios', verbose_name='Copiar de ')),
            ],
            options={
                'verbose_name': ' Cenário',
                'verbose_name_plural': ' Cenários',
                'ordering': ['-cen_ativo', '-cen_grupo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TbEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('emp_tipo', models.CharField(choices=[('G', 'Greenfield'), ('B', 'Brownfield')], max_length=10, verbose_name='Tipo')),
                ('emp_descricao', models.TextField(null=True, verbose_name='Descrição')),
                ('emp_moeda', models.CharField(choices=[('BRL', 'REAL'), ('USD', 'DÓLAR'), ('EUR', 'EURO')], default='BRL', max_length=3, verbose_name='Moeda')),
                ('emp_moeda_imagem', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Imagem da Moeda')),
                ('emp_logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo')),
                ('emp_fluxo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Fluxo de Produção')),
            ],
            options={
                'verbose_name': '  Empresa',
                'verbose_name_plural': '  Empresa',
            },
        ),
        migrations.CreateModel(
            name='TbGlossario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glo_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('glo_descricao', models.TextField(verbose_name='Descrição')),
                ('glo_imagem', models.ImageField(blank=True, null=True, upload_to='parameters', verbose_name='Imagem')),
                ('glo_fonte', models.FileField(blank=True, null=True, upload_to='parameters', verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Glossário',
                'verbose_name_plural': 'Glossário',
                'ordering': ['glo_nome'],
            },
        ),
        migrations.CreateModel(
            name='TbCenariosDaugther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_order', models.IntegerField(blank=True, null=True, verbose_name='Ano/Mês')),
                ('otimizar', models.BooleanField(default=True, verbose_name='Otimizar')),
                ('dau_valor_1', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Vendas')),
                ('dau_valor_2', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Variável')),
                ('dau_valor_3', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Inbound')),
                ('dau_valor_4', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Outbound')),
                ('dau_valor_5', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Manut.')),
                ('dau_valor_6', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Margem')),
                ('dau_valor_7', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Fixo')),
                ('dau_valor_8', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='EBTIDA')),
                ('dau_valor_9', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='EBTIDA (%)')),
                ('dau_valor_10', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='D&A')),
                ('dau_valor_11', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='IR (%)')),
                ('dau_valor_12', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='MP')),
                ('dau_valor_13', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='WIP')),
                ('dau_valor_14', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='PF')),
                ('dau_valor_15', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Total Est.')),
                ('dau_valor_16', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Receber')),
                ('dau_valor_17', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='Pagar')),
                ('dau_valor_18', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='OWCR')),
                ('dau_valor_19', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='CAPEX')),
                ('dau_valor_20', models.DecimalField(decimal_places=0, default=0.0, max_digits=18, verbose_name='OFCF')),
                ('flag', models.IntegerField(blank=True, null=True, verbose_name='Solúção')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['dau_order'],
            },
        ),
    ]
