# Generated by Django 4.1.7 on 2023-12-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('tabelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcenarios',
            name='cen_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbgrupocenarios', verbose_name='Grupo'),
        ),
    ]
