# Generated by Django 4.1.7 on 2024-04-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcenarios',
            name='cen_nome',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nome'),
        ),
    ]
