# Generated by Django 4.1.7 on 2024-09-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_alter_tbcenarios_cen_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCenariosDaugther1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('quem', models.CharField(blank=True, max_length=20, null=True, verbose_name='Quem Criou/Alterou')),
                ('o_que', models.TextField(verbose_name='O Que')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbcenarios', verbose_name='Mãe')),
            ],
            options={
                'verbose_name': 'Diário de Bordo',
                'verbose_name_plural': 'Diário de Bordo',
                'ordering': ['-data'],
            },
        ),
    ]
