# Generated by Django 4.1.7 on 2024-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_tbcenariosdaugther1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcenariosdaugther1',
            name='quem',
            field=models.CharField(default='a', max_length=20, verbose_name='Quem Criou/Alterou'),
            preserve_default=False,
        ),
    ]
