# Generated by Django 4.1.7 on 2024-09-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_alter_tbcenariosdaugther1_quem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcenariosdaugther1',
            name='quem',
        ),
    ]
