# Generated by Django 4.1.7 on 2025-02-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0006_remove_tbcenariosdaugther1_quem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcenarios',
            name='cen_desvio_producao',
            field=models.BooleanField(default=True, verbose_name='Considerar Desvio = Produção'),
        ),
    ]
