# Generated by Django 4.1.7 on 2025-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0007_tbcenarios_cen_desvio_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcenarios',
            name='cen_desvio_producao',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Considerar Desvio = Produção'),
        ),
    ]
