# Generated by Django 4.1.7 on 2025-02-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0009_alter_tbcenarios_cen_desvio_producao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcenarios',
            name='cen_desvio_producao',
        ),
    ]
