# Generated by Django 4.1.7 on 2025-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0010_remove_tbcenarios_cen_desvio_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcenarios',
            name='cen_nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
