# Generated by Django 4.1.7 on 2025-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0011_alter_tbcenarios_cen_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcenarios',
            name='cen_nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
