# Generated by Django 4.2.30 on 2026-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0012_alter_tbcenarios_cen_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prompt_sistema', models.TextField(help_text='Instruções para o LangChain')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comando_usuario', models.TextField()),
                ('resposta_ia', models.TextField()),
            ],
        ),
    ]
