# Generated by Django 4.2.30 on 2026-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0013_agenteconfig_historicoagente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Relatório')),
                ('arquivo', models.FileField(upload_to='relatorios_pdf/', verbose_name='Arquivo PDF')),
                ('texto_extraido', models.TextField(blank=True, help_text='Gerado automaticamente após salvar.', null=True, verbose_name='Texto Extraído do PDF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível para a IA')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relatório PDF',
                'verbose_name_plural': 'Relatórios PDF',
            },
        ),
        migrations.AlterModelOptions(
            name='agenteconfig',
            options={'ordering': ['nome'], 'verbose_name': ' Comportamento Agente IA', 'verbose_name_plural': ' Comportamentos Agente IA'},
        ),
        migrations.AlterModelOptions(
            name='historicoagente',
            options={'ordering': ['-data'], 'verbose_name': 'Histórico Agente IA', 'verbose_name_plural': 'Históricos Agente IA'},
        ),
        migrations.AlterModelOptions(
            name='tbcenarios',
            options={'ordering': ['-cen_ativo', '-cen_grupo', 'id'], 'verbose_name': '   Cenário', 'verbose_name_plural': '   Cenários'},
        ),
        migrations.AlterModelOptions(
            name='tbempresa',
            options={'verbose_name': '    Empresa', 'verbose_name_plural': '    Empresa'},
        ),
        migrations.AlterModelOptions(
            name='tbglossario',
            options={'ordering': ['glo_nome'], 'verbose_name': '  Glossário', 'verbose_name_plural': '  Glossário'},
        ),
        migrations.AlterField(
            model_name='agenteconfig',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='agenteconfig',
            name='prompt_sistema',
            field=models.TextField(help_text='Instruções para o Agente IA', verbose_name='Instruções'),
        ),
        migrations.AlterField(
            model_name='historicoagente',
            name='comando_usuario',
            field=models.TextField(verbose_name='Pergunta Usuário'),
        ),
        migrations.AlterField(
            model_name='historicoagente',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='historicoagente',
            name='resposta_ia',
            field=models.TextField(verbose_name='Resposta Agente IA'),
        ),
    ]
