# Generated by Django 4.2.30 on 2026-09-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0014_relatoriopdf_alter_agenteconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriopdf',
            name='texto_extraido',
        ),
    ]
