# Generated by Django 4.2.30 on 2026-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0017_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_trocar_cenario',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o usuário não verá a opção de ativar outro cenário.', verbose_name='Pode trocar cenário ativo'),
        ),
    ]
