# Generated by Django 4.2.30 on 2026-09-11 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parameters', '0018_perfilusuario_pode_trocar_cenario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbcenarios',
            options={'ordering': ['id'], 'verbose_name': '   Cenário', 'verbose_name_plural': '   Cenários'},
        ),
        migrations.CreateModel(
            name='EstadoConversaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluxo_ativo', models.CharField(blank=True, choices=[('criar_cenario', 'Criar Cenário')], max_length=30, null=True, verbose_name='Fluxo em andamento')),
                ('etapa_atual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etapa atual')),
                ('dados_coletados', models.JSONField(blank=True, default=dict, verbose_name='Dados coletados')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Conversa do Agente',
                'verbose_name_plural': 'Estados de Conversa do Agente',
            },
        ),
    ]
