# Generated by Django 4.2.30 on 2026-09-13 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0019_alter_tbcenarios_options_estadoconversaagente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcenarios',
            name='eh_cenario_base',
            field=models.BooleanField(default=False, verbose_name='É Cenário Base'),
        ),
        migrations.AddField(
            model_name='tbcenarios',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tbcenarios',
            name='numero_sequencial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número do Cenário'),
        ),
        migrations.AddField(
            model_name='tbempresa',
            name='proximo_numero_cenario',
            field=models.IntegerField(default=1, verbose_name='Próximo Número de Cenário'),
        ),
        migrations.AlterField(
            model_name='tbcenarios',
            name='cen_copiar_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.tbcenarios', verbose_name='Copiar de '),
        ),
    ]
