# Generated by Django 4.2.30 on 2026-09-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0020_tbcenarios_eh_cenario_base_tbcenarios_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='A empresa desse usuário -- ele só vê os dados dela. Não se aplica a superusuários.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='empresa_ativa',
            field=models.ForeignKey(blank=True, help_text='Só usado por superusuários -- em qual empresa ele está trabalhando agora.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superusuarios_com_esta_ativa', to='parameters.tbempresa', verbose_name='Empresa Ativa (superusuário)'),
        ),
    ]
