# Generated by Django 4.2.30 on 2026-09-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0021_perfilusuario_empresa_perfilusuario_empresa_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcenarios',
            name='cen_nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='tbcenarios',
            constraint=models.UniqueConstraint(fields=('cen_nome', 'empresa'), name='cenario_nome_unico_por_empresa'),
        ),
    ]
