# Generated by Django 4.2.30 on 2026-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0022_alter_tbcenarios_cen_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cenarios_ativos_por_empresa',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cenários ativos por empresa (memória)'),
        ),
    ]
