# Generated by Django 4.2.30 on 2026-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0023_perfilusuario_cenarios_ativos_por_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcenarios',
            name='numero_sequencial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cenário'),
        ),
    ]
