# Generated by Django 4.2.30 on 2026-09-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0024_alter_tbcenarios_numero_sequencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbglossario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
    ]
