# Generated by Django 4.2.30 on 2026-09-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0025_tbglossario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='eh_superuser_empresa',
            field=models.BooleanField(default=False, help_text='Tem todos os poderes de superusuário, mas restritos à própria empresa (não pode trocar de empresa nem ver dados de outras).', verbose_name='Superusuário da Empresa'),
        ),
    ]
