# Generated by Django 4.2.30 on 2026-09-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0026_perfilusuario_eh_superuser_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriopdf',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
    ]
