# Generated by Django 4.2.30 on 2026-09-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0027_relatoriopdf_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppOpcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(help_text='Precisa bater com o nome real do app Django (ex: "custo_ferbasa").', max_length=50, unique=True, verbose_name='App (nome técnico)')),
                ('nome_exibicao', models.CharField(max_length=100, verbose_name='Nome de Exibição')),
            ],
            options={
                'verbose_name': '   App Opcional',
                'verbose_name_plural': '   Apps Opcionais',
                'ordering': ['nome_exibicao'],
            },
        ),
        migrations.AddField(
            model_name='tbempresa',
            name='apps_habilitados',
            field=models.ManyToManyField(blank=True, to='parameters.appopcional', verbose_name='Apps Habilitados'),
        ),
    ]
