# Generated by Django 4.2.30 on 2026-09-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0028_appopcional_tbempresa_apps_habilitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='idioma',
            field=models.CharField(blank=True, choices=[('pt-br', 'Português'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('zh-hans', '中文（简体）')], help_text='Se vazio, usa o idioma padrão da empresa.', max_length=10, null=True, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='tbempresa',
            name='idioma_padrao',
            field=models.CharField(choices=[('pt-br', 'Português'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano'), ('zh-hans', '中文（简体）')], default='pt-br', max_length=10, verbose_name='Idioma Padrão'),
        ),
    ]
