# Generated by Django 4.2.30 on 2026-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0029_perfilusuario_idioma_tbempresa_idioma_padrao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatoriopdf',
            options={'verbose_name': 'Relatório Consulta IA', 'verbose_name_plural': 'Relatórios Consulta IA'},
        ),
        migrations.AlterField(
            model_name='relatoriopdf',
            name='arquivo',
            field=models.FileField(upload_to='relatorios_pdf/', verbose_name='Arquivo'),
        ),
    ]
