# Generated by Django 4.2.30 on 2026-09-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0030_alter_relatoriopdf_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ex: "Indicadores", "Câmbio", "Cenário".', max_length=50, verbose_name='Categoria')),
                ('chave', models.CharField(help_text='Identificador técnico usado no código -- não muda depois de criado.', max_length=50, verbose_name='Ação (chave técnica)')),
                ('nome_exibicao', models.CharField(max_length=150, verbose_name='Nome de Exibição')),
            ],
            options={
                'verbose_name': '   Ação Comum',
                'verbose_name_plural': '   Ações Comuns',
                'ordering': ['categoria', 'chave'],
                'unique_together': {('categoria', 'chave')},
            },
        ),
        migrations.AddField(
            model_name='tbempresa',
            name='acoes_comuns_habilitadas',
            field=models.ManyToManyField(blank=True, to='parameters.acaocomum', verbose_name='Ações Comuns Habilitadas'),
        ),
    ]
