# Generated by Django 4.2.30 on 2026-09-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0031_acaocomum_tbempresa_acoes_comuns_habilitadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfig',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicoagente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.tbempresa', verbose_name='Empresa'),
        ),
    ]
