# Generated by Django 4.2.30 on 2026-09-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0032_agenteconfig_empresa_historicoagente_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acaocomum',
            options={'ordering': ['categoria', 'chave'], 'verbose_name': 'Ação Comum IA', 'verbose_name_plural': 'Ações Comuns IA'},
        ),
        migrations.AlterModelOptions(
            name='agenteconfig',
            options={'ordering': ['nome'], 'verbose_name': 'Comportamento Agente IA', 'verbose_name_plural': 'Comportamentos Agente IA'},
        ),
        migrations.AlterModelOptions(
            name='appopcional',
            options={'ordering': ['nome_exibicao'], 'verbose_name': 'App Opcional', 'verbose_name_plural': 'Apps Opcionais'},
        ),
        migrations.AlterModelOptions(
            name='tbcenarios',
            options={'ordering': ['id'], 'verbose_name': 'Cenário', 'verbose_name_plural': 'Cenários'},
        ),
        migrations.AlterModelOptions(
            name='tbempresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
        migrations.AlterModelOptions(
            name='tbglossario',
            options={'ordering': ['glo_nome'], 'verbose_name': 'Glossário', 'verbose_name_plural': 'Glossário'},
        ),
    ]
