# Generated by Django 4.2.30 on 2026-09-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0033_alter_acaocomum_options_alter_agenteconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatoriopdf',
            options={'verbose_name': 'Relatório Agente IA', 'verbose_name_plural': 'Relatórios Agente IA'},
        ),
        migrations.CreateModel(
            name='ArquivoAtualizacaoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos_atualizacao_agente/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.tbempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Arquivo de Atualização do Agente',
                'verbose_name_plural': 'Arquivos de Atualização do Agente',
            },
        ),
    ]
