# Generated by Django 4.2.30 on 2026-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0034_alter_relatoriopdf_options_arquivoatualizacaoagente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='acoes_comuns_restritas',
            field=models.ManyToManyField(blank=True, help_text='Ações do menu "Ações Comuns" que ESTE usuário específico não deve ver, mesmo habilitadas para a empresa dele. Só é possível restringir ações que a empresa já tem habilitadas.', related_name='usuarios_com_restricao', to='parameters.acaocomum', verbose_name='Ações Comuns Restritas (deste usuário)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apps_restritos',
            field=models.ManyToManyField(blank=True, help_text='Apps que ESTE usuário específico não deve ver, mesmo habilitados para a empresa dele. Só é possível restringir apps que a empresa já tem habilitados.', related_name='usuarios_com_restricao', to='parameters.appopcional', verbose_name='Apps Restritos (deste usuário)'),
        ),
    ]
