# Generated by Django 4.2.30 on 2026-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0035_perfilusuario_acoes_comuns_restritas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pode_acessar_agente_ia',
            field=models.BooleanField(default=False, help_text='Se marcado, o usuário pode acessar o Agente IA (chat).', verbose_name='Acesso ao Agente IA'),
        ),
    ]
