# Generated by Django 4.2.30 on 2026-09-23 08:55

"""
🌟 NOVO: migração de DADOS (não de schema) -- copia o acesso ao Agente IA
que hoje vem do Grupo "Agente de IA" pro novo campo
PerfilUsuario.pode_acessar_agente_ia, garantindo que ninguém perde acesso
na troca do mecanismo antigo (Grupo) pro novo (campo no perfil).

COMO USAR:
1. Rode primeiro:  python manage.py makemigrations parameters
   (isso gera a migração de SCHEMA que cria o campo pode_acessar_agente_ia
   -- vai ter um nome tipo "00XX_perfilusuario_pode_acessar_agente_ia.py")
2. Rode depois:     python manage.py makemigrations parameters --empty --name migrar_acesso_agente_ia_do_grupo
   (isso cria um arquivo de migração vazio, já com o nome certo e a
   dependência apontando pra migração do passo 1, automaticamente)
3. Abra o arquivo vazio gerado no passo 2 e substitua o conteúdo dele
   pelo conteúdo deste arquivo aqui (mantendo o "dependencies" que o
   Django já preencheu sozinho no passo 2 -- não precisa mexer nele).
4. Rode:            python manage.py migrate parameters

Depois de confirmar que todo mundo que devia continuar com acesso
realmente está com "Acesso ao Agente IA" marcado no perfil, o Grupo
"Agente de IA" pode ser removido manualmente (Admin -> Autenticação e
Autorização -> Grupos) -- não é mais usado em nenhum lugar do código.
"""
from django.db import migrations


def migrar_acesso_grupo_para_campo(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    PerfilUsuario = apps.get_model('parameters', 'PerfilUsuario')

    grupo = Group.objects.filter(name='Agente de IA').first()
    if grupo is None:
        # Grupo já não existe (ou nunca existiu nesse ambiente) -- nada
        # a copiar.
        return

    usuarios_do_grupo_ids = list(grupo.user_set.values_list('id', flat=True))
    PerfilUsuario.objects.filter(usuario_id__in=usuarios_do_grupo_ids).update(pode_acessar_agente_ia=True)


def reverter(apps, schema_editor):
    # 🌟 Propositalmente não desfaz nada -- reverter essa migração não
    # deveria remover acesso que um administrador já tenha ajustado
    # manualmente depois de aplicada.
    pass


class Migration(migrations.Migration):

    # 🌟 O Django preenche isso sozinho quando você roda o comando do
    # passo 2 das instruções acima -- não precisa editar essa linha.
    dependencies = [
        ('parameters', '0036_perfilusuario_pode_acessar_agente_ia'),
    ]

    operations = [
        migrations.RunPython(migrar_acesso_grupo_para_campo, reverter),
    ]
