# Generated by Django 4.2.30 on 2026-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0037_migrar_acesso_agente_ia_do_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcenarios',
            name='ultimas_alteracoes',
            field=models.TextField(blank=True, help_text='Histórico de alterações em outras tabelas que fizeram este cenário ficar "ALTERADO" -- uma linha por alteração, preenchido automaticamente.', null=True, verbose_name='Últimas Alterações'),
        ),
    ]
