# Generated by Django 4.2.30 on 2026-09-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0038_tbcenarios_ultimas_alteracoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcenarios',
            name='cen_ativo',
        ),
    ]
