# Generated by Django 4.2.30 on 2026-09-28 00:56

from django.db import migrations, models
import django.db.models.deletion
import parameters.contexto_usuario


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tabelas', '0004_alter_tbcustoitem_cus_ite_tipo_and_more'),
        ('parameters', '0039_remove_tbcenarios_cen_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcenarios',
            name='cen_grupo',
            field=models.ForeignKey(blank=True, limit_choices_to=parameters.contexto_usuario.limit_choices_to_empresa_ativa, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelas.tbgrupocenarios', verbose_name='Grupo'),
        ),
        migrations.CreateModel(
            name='TbGrupoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.tbempresa', verbose_name='Empresa')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_vinculo', to='auth.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Empresa do Grupo',
                'verbose_name_plural': 'Empresa dos Grupos',
            },
        ),
    ]
