# Generated by Django 4.2.30 on 2026-09-28 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0040_alter_tbcenarios_cen_grupo_tbgrupoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telefone_whatsapp',
            field=models.CharField(blank=True, help_text='Com código do país e DDD (ex.: 5511912345678). Só superusuários recebem os alertas do Agente IA por WhatsApp.', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[\\d\\s\\+\\-\\(\\)]{10,20}$', message='Informe o telefone com código do país e DDD, ex.: 5511912345678.')], verbose_name='Celular / WhatsApp'),
        ),
    ]
