# Generated by Django 4.2.30 on 2026-09-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0041_perfilusuario_telefone_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefone_whatsapp',
        ),
    ]
